import Sqpack.Exact.Packs.N102.C0
import Sqpack.Exact.Packs.N102.C1
import Sqpack.Exact.Packs.N102.C2
import Sqpack.Exact.Packs.N102.C3
import Sqpack.Exact.Packs.N102.C4

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 102, the certificate in `Data`, squares checked in 5 chunks. -/

namespace UnitSquarePacking.EC.N102

set_option maxHeartbeats 0

theorem ok (i : Fin 102) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  exact chunk_4 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(102) ≤ S*`, `S*` the root of `pS` in `[10.6071746802, 10.6071746802]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((106071746801760511253425231780890033270787/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((106071746801760511253425233780890033270787/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 102 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N102
