import Sqpack.Exact.Packs.N107.C0
import Sqpack.Exact.Packs.N107.C1
import Sqpack.Exact.Packs.N107.C2
import Sqpack.Exact.Packs.N107.C3
import Sqpack.Exact.Packs.N107.C4

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 107, the certificate in `Data`, squares checked in 5 chunks. -/

namespace UnitSquarePacking.EC.N107

set_option maxHeartbeats 0

theorem ok (i : Fin 107) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  exact chunk_4 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(107) ≤ S*`, `S*` the root of `pS` in `[10.8466671928, 10.8466671928]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((108466671928434897829433144909582979088797/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((108466671928434897829433146909582979088797/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 107 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N107
