import Sqpack.Exact.Packs.N109.C0
import Sqpack.Exact.Packs.N109.C1
import Sqpack.Exact.Packs.N109.C2
import Sqpack.Exact.Packs.N109.C3
import Sqpack.Exact.Packs.N109.C4

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 109, the certificate in `Data`, squares checked in 5 chunks. -/

namespace UnitSquarePacking.EC.N109

set_option maxHeartbeats 0

theorem ok (i : Fin 109) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  exact chunk_4 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(109) ≤ S*`, `S*` the root of `pS` in `[10.9497474683, 10.9497474683]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((109497474683058326708059104347339432749939/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((109497474683058326708059106347339432749939/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 109 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

/-- `s(109) ≤ 6 + 7 * √2 / 2`: the side in closed form (`ExactQuad.packs_quad`). -/
theorem packs_closed : Packs 109 (6 + 7 * √2 / 2) := by
  have h := packs_quad (P := 6) (Q := (7/2 : ℚ)) (D := 2) (lo := (1414213562373095048801688724209/1000000000000000000000000000000 : ℚ)) (hi := (141421356237309504880168872421/100000000000000000000000000000 : ℚ)) packs (by decide +kernel)
  convert h using 1; push_cast; ring

theorem minSide_le_closed : minSide 109 ≤ 6 + 7 * √2 / 2 :=
  csInf_le ⟨0, fun _ hs => nonneg_of_packs_q (by norm_num) hs⟩ packs_closed

end UnitSquarePacking.EC.N109
