import Sqpack.Exact.Packs.N11.C0

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 11, the certificate in `Data`, squares checked in 1 chunks. -/

namespace UnitSquarePacking.EC.N11

set_option maxHeartbeats 0

theorem ok (i : Fin 11) : boxOK cert i = true ∧ rowOK cert i = true := by
  exact chunk_0 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(11) ≤ S*`, `S*` the root of `pS` in `[3.87708359002, 3.87708359002]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((7754167180045628354615793920201925412753/2000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((7754167180045628354615794320201925412753/2000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 11 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N11
