import Sqpack.Exact.Packs.N114.C0
import Sqpack.Exact.Packs.N114.C1
import Sqpack.Exact.Packs.N114.C2
import Sqpack.Exact.Packs.N114.C3
import Sqpack.Exact.Packs.N114.C4

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 114, the certificate in `Data`, squares checked in 5 chunks. -/

namespace UnitSquarePacking.EC.N114

set_option maxHeartbeats 0

theorem ok (i : Fin 114) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  exact chunk_4 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(114) ≤ S*`, `S*` the root of `pS` in `[11, 11]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((109999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((110000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 114 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N114
