import Sqpack.Exact.Packs.N122.C0
import Sqpack.Exact.Packs.N122.C1
import Sqpack.Exact.Packs.N122.C2
import Sqpack.Exact.Packs.N122.C3
import Sqpack.Exact.Packs.N122.C4

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 122, the certificate in `Data`, squares checked in 5 chunks. -/

namespace UnitSquarePacking.EC.N122

set_option maxHeartbeats 0

theorem ok (i : Fin 122) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  exact chunk_4 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(122) ≤ S*`, `S*` the root of `pS` in `[11.5355339059, 11.5355339059]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((57677669529663688110021108552621225982121/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((57677669529663688110021109552621225982121/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 122 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

/-- `s(122) ≤ 8 + 5 * √2 / 2`: the side in closed form (`ExactQuad.packs_quad`). -/
theorem packs_closed : Packs 122 (8 + 5 * √2 / 2) := by
  have h := packs_quad (P := 8) (Q := (5/2 : ℚ)) (D := 2) (lo := (1414213562373095048801688724209/1000000000000000000000000000000 : ℚ)) (hi := (141421356237309504880168872421/100000000000000000000000000000 : ℚ)) packs (by decide +kernel)
  convert h using 1; push_cast; ring

theorem minSide_le_closed : minSide 122 ≤ 8 + 5 * √2 / 2 :=
  csInf_le ⟨0, fun _ hs => nonneg_of_packs_q (by norm_num) hs⟩ packs_closed

end UnitSquarePacking.EC.N122
