import Sqpack.Exact.Packs.N129.C0
import Sqpack.Exact.Packs.N129.C1
import Sqpack.Exact.Packs.N129.C2
import Sqpack.Exact.Packs.N129.C3
import Sqpack.Exact.Packs.N129.C4
import Sqpack.Exact.Packs.N129.C5
import Sqpack.Exact.Packs.N129.C6
import Sqpack.Exact.Packs.N129.C7
import Sqpack.Exact.Packs.N129.C8
import Sqpack.Exact.Packs.N129.C9
import Sqpack.Exact.Packs.N129.C10
import Sqpack.Exact.Packs.N129.C11
import Sqpack.Exact.Packs.N129.C12

/-! Generated by `search/exact/lean_cert.py --split 10`: n = 129, the certificate in `Data`, squares checked in 13 chunks. -/

namespace UnitSquarePacking.EC.N129

set_option maxHeartbeats 0

theorem ok (i : Fin 129) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 10
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 20
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 30
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 40
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 50
  · exact chunk_4 i (by omega) h4
  by_cases h5 : i.val < 60
  · exact chunk_5 i (by omega) h5
  by_cases h6 : i.val < 70
  · exact chunk_6 i (by omega) h6
  by_cases h7 : i.val < 80
  · exact chunk_7 i (by omega) h7
  by_cases h8 : i.val < 90
  · exact chunk_8 i (by omega) h8
  by_cases h9 : i.val < 100
  · exact chunk_9 i (by omega) h9
  by_cases h10 : i.val < 110
  · exact chunk_10 i (by omega) h10
  by_cases h11 : i.val < 120
  · exact chunk_11 i (by omega) h11
  exact chunk_12 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(129) ≤ S*`, `S*` the root of `pS` in `[11.8813062181, 11.8813062181]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((11881306218090003063213703846542229069947/1000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((11881306218090003063213704046542229069947/1000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 129 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N129
