import Sqpack.Exact.Packs.N138.C0
import Sqpack.Exact.Packs.N138.C1
import Sqpack.Exact.Packs.N138.C2
import Sqpack.Exact.Packs.N138.C3
import Sqpack.Exact.Packs.N138.C4
import Sqpack.Exact.Packs.N138.C5

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 138, the certificate in `Data`, squares checked in 6 chunks. -/

namespace UnitSquarePacking.EC.N138

set_option maxHeartbeats 0

theorem ok (i : Fin 138) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 125
  · exact chunk_4 i (by omega) h4
  exact chunk_5 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(138) ≤ S*`, `S*` the root of `pS` in `[12, 12]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((119999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((120000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 138 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N138
