import Sqpack.Exact.Packs.N146.C0
import Sqpack.Exact.Packs.N146.C1
import Sqpack.Exact.Packs.N146.C2
import Sqpack.Exact.Packs.N146.C3
import Sqpack.Exact.Packs.N146.C4
import Sqpack.Exact.Packs.N146.C5

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 146, the certificate in `Data`, squares checked in 6 chunks. -/

namespace UnitSquarePacking.EC.N146

set_option maxHeartbeats 0

theorem ok (i : Fin 146) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 125
  · exact chunk_4 i (by omega) h4
  exact chunk_5 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(146) ≤ S*`, `S*` the root of `pS` in `[12.6009077785, 12.6009077785]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((126009077785130182401120309470790924733093/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((126009077785130182401120311470790924733093/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 146 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N146
