import Sqpack.Exact.Packs.N146.C0
import Sqpack.Exact.Packs.N146.C1
import Sqpack.Exact.Packs.N146.C2
import Sqpack.Exact.Packs.N146.C3
import Sqpack.Exact.Packs.N146.C4
import Sqpack.Exact.Packs.N146.C5
import Sqpack.Exact.Packs.N146.C6
import Sqpack.Exact.Packs.N146.C7
import Sqpack.Exact.Packs.N146.C8
import Sqpack.Exact.Packs.N146.C9
import Sqpack.Exact.Packs.N146.C10
import Sqpack.Exact.Packs.N146.C11
import Sqpack.Exact.Packs.N146.C12
import Sqpack.Exact.Packs.N146.C13
import Sqpack.Exact.Packs.N146.C14

/-! Generated by `search/exact/lean_cert.py --split 10`: n = 146, the certificate in `Data`, squares checked in 15 chunks. -/

namespace UnitSquarePacking.EC.N146

set_option maxHeartbeats 0

theorem ok (i : Fin 146) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 10
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 20
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 30
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 40
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 50
  · exact chunk_4 i (by omega) h4
  by_cases h5 : i.val < 60
  · exact chunk_5 i (by omega) h5
  by_cases h6 : i.val < 70
  · exact chunk_6 i (by omega) h6
  by_cases h7 : i.val < 80
  · exact chunk_7 i (by omega) h7
  by_cases h8 : i.val < 90
  · exact chunk_8 i (by omega) h8
  by_cases h9 : i.val < 100
  · exact chunk_9 i (by omega) h9
  by_cases h10 : i.val < 110
  · exact chunk_10 i (by omega) h10
  by_cases h11 : i.val < 120
  · exact chunk_11 i (by omega) h11
  by_cases h12 : i.val < 130
  · exact chunk_12 i (by omega) h12
  by_cases h13 : i.val < 140
  · exact chunk_13 i (by omega) h13
  exact chunk_14 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(146) ≤ S*`, `S*` the root of `pS` in `[12.6009077785, 12.6009077785]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((126009077785130182401120309470790924733093/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((126009077785130182401120311470790924733093/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 146 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N146
