import Sqpack.Exact.Packs.N153.C0
import Sqpack.Exact.Packs.N153.C1
import Sqpack.Exact.Packs.N153.C2
import Sqpack.Exact.Packs.N153.C3
import Sqpack.Exact.Packs.N153.C4
import Sqpack.Exact.Packs.N153.C5
import Sqpack.Exact.Packs.N153.C6

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 153, the certificate in `Data`, squares checked in 7 chunks. -/

namespace UnitSquarePacking.EC.N153

set_option maxHeartbeats 0

theorem ok (i : Fin 153) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 125
  · exact chunk_4 i (by omega) h4
  by_cases h5 : i.val < 150
  · exact chunk_5 i (by omega) h5
  exact chunk_6 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(153) ≤ S*`, `S*` the root of `pS` in `[12.881666757, 12.881666757]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((128816667570090046248235120489096372070621/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((128816667570090046248235122489096372070621/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 153 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N153
