import Sqpack.Exact.Packs.N160.C0
import Sqpack.Exact.Packs.N160.C1
import Sqpack.Exact.Packs.N160.C2
import Sqpack.Exact.Packs.N160.C3
import Sqpack.Exact.Packs.N160.C4
import Sqpack.Exact.Packs.N160.C5
import Sqpack.Exact.Packs.N160.C6

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 160, the certificate in `Data`, squares checked in 7 chunks. -/

namespace UnitSquarePacking.EC.N160

set_option maxHeartbeats 0

theorem ok (i : Fin 160) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 125
  · exact chunk_4 i (by omega) h4
  by_cases h5 : i.val < 150
  · exact chunk_5 i (by omega) h5
  exact chunk_6 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(160) ≤ S*`, `S*` the root of `pS` in `[13, 13]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((129999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((130000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 160 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N160
