import Sqpack.Exact.Packs.N19.C0

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 19, the certificate in `Data`, squares checked in 1 chunks. -/

namespace UnitSquarePacking.EC.N19

set_option maxHeartbeats 0

theorem ok (i : Fin 19) : boxOK cert i = true ∧ rowOK cert i = true := by
  exact chunk_0 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(19) ≤ S*`, `S*` the root of `pS` in `[4.88561808316, 4.88561808316]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((24428090415820633658677924328064653857131/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((24428090415820633658677925328064653857131/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 19 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

/-- `s(19) ≤ 3 + 4 * √2 / 3`: the side in closed form (`ExactQuad.packs_quad`). -/
theorem packs_closed : Packs 19 (3 + 4 * √2 / 3) := by
  have h := packs_quad (P := 3) (Q := (4/3 : ℚ)) (D := 2) (lo := (1414213562373095048801688724209/1000000000000000000000000000000 : ℚ)) (hi := (141421356237309504880168872421/100000000000000000000000000000 : ℚ)) packs (by decide +kernel)
  convert h using 1; push_cast; ring

theorem minSide_le_closed : minSide 19 ≤ 3 + 4 * √2 / 3 :=
  csInf_le ⟨0, fun _ hs => nonneg_of_packs_q (by norm_num) hs⟩ packs_closed

end UnitSquarePacking.EC.N19
