import Sqpack.Exact.Packs.N204.C0
import Sqpack.Exact.Packs.N204.C1
import Sqpack.Exact.Packs.N204.C2
import Sqpack.Exact.Packs.N204.C3
import Sqpack.Exact.Packs.N204.C4
import Sqpack.Exact.Packs.N204.C5
import Sqpack.Exact.Packs.N204.C6
import Sqpack.Exact.Packs.N204.C7
import Sqpack.Exact.Packs.N204.C8

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 204, the certificate in `Data`, squares checked in 9 chunks. -/

namespace UnitSquarePacking.EC.N204

set_option maxHeartbeats 0

theorem ok (i : Fin 204) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 125
  · exact chunk_4 i (by omega) h4
  by_cases h5 : i.val < 150
  · exact chunk_5 i (by omega) h5
  by_cases h6 : i.val < 175
  · exact chunk_6 i (by omega) h6
  by_cases h7 : i.val < 200
  · exact chunk_7 i (by omega) h7
  exact chunk_8 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(204) ≤ S*`, `S*` the root of `pS` in `[14.8228756555, 14.8228756555]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((148228756555322952952508077768196302128551/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((148228756555322952952508079768196302128551/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 204 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

/-- `s(204) ≤ 27 / 2 + √7 / 2`: the side in closed form (`ExactQuad.packs_quad`). -/
theorem packs_closed : Packs 204 (27 / 2 + √7 / 2) := by
  have h := packs_quad (P := (27/2 : ℚ)) (Q := (1/2 : ℚ)) (D := 7) (lo := (2645751311064590590501615753639/1000000000000000000000000000000 : ℚ)) (hi := (66143782776614764762540393841/25000000000000000000000000000 : ℚ)) packs (by decide +kernel)
  convert h using 1; push_cast; ring

theorem minSide_le_closed : minSide 204 ≤ 27 / 2 + √7 / 2 :=
  csInf_le ⟨0, fun _ hs => nonneg_of_packs_q (by norm_num) hs⟩ packs_closed

end UnitSquarePacking.EC.N204
