import Sqpack.Exact.Packs.N215.C0
import Sqpack.Exact.Packs.N215.C1
import Sqpack.Exact.Packs.N215.C2
import Sqpack.Exact.Packs.N215.C3
import Sqpack.Exact.Packs.N215.C4
import Sqpack.Exact.Packs.N215.C5
import Sqpack.Exact.Packs.N215.C6
import Sqpack.Exact.Packs.N215.C7
import Sqpack.Exact.Packs.N215.C8

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 215, the certificate in `Data`, squares checked in 9 chunks. -/

namespace UnitSquarePacking.EC.N215

set_option maxHeartbeats 0

theorem ok (i : Fin 215) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 125
  · exact chunk_4 i (by omega) h4
  by_cases h5 : i.val < 150
  · exact chunk_5 i (by omega) h5
  by_cases h6 : i.val < 175
  · exact chunk_6 i (by omega) h6
  by_cases h7 : i.val < 200
  · exact chunk_7 i (by omega) h7
  exact chunk_8 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(215) ≤ S*`, `S*` the root of `pS` in `[15, 15]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((149999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((150000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 215 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N215
