import Sqpack.Exact.Packs.N23.C0

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 23, the certificate in `Data`, squares checked in 1 chunks. -/

namespace UnitSquarePacking.EC.N23

set_option maxHeartbeats 0

theorem ok (i : Fin 23) : boxOK cert i = true ∧ rowOK cert i = true := by
  exact chunk_0 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(23) ≤ S*`, `S*` the root of `pS` in `[5, 5]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((49999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((50000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 23 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N23
