import Sqpack.Exact.Packs.N290.C0
import Sqpack.Exact.Packs.N290.C1
import Sqpack.Exact.Packs.N290.C2
import Sqpack.Exact.Packs.N290.C3
import Sqpack.Exact.Packs.N290.C4
import Sqpack.Exact.Packs.N290.C5
import Sqpack.Exact.Packs.N290.C6
import Sqpack.Exact.Packs.N290.C7
import Sqpack.Exact.Packs.N290.C8
import Sqpack.Exact.Packs.N290.C9
import Sqpack.Exact.Packs.N290.C10
import Sqpack.Exact.Packs.N290.C11

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 290, the certificate in `Data`, squares checked in 12 chunks. -/

namespace UnitSquarePacking.EC.N290

set_option maxHeartbeats 0

theorem ok (i : Fin 290) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  by_cases h3 : i.val < 100
  · exact chunk_3 i (by omega) h3
  by_cases h4 : i.val < 125
  · exact chunk_4 i (by omega) h4
  by_cases h5 : i.val < 150
  · exact chunk_5 i (by omega) h5
  by_cases h6 : i.val < 175
  · exact chunk_6 i (by omega) h6
  by_cases h7 : i.val < 200
  · exact chunk_7 i (by omega) h7
  by_cases h8 : i.val < 225
  · exact chunk_8 i (by omega) h8
  by_cases h9 : i.val < 250
  · exact chunk_9 i (by omega) h9
  by_cases h10 : i.val < 275
  · exact chunk_10 i (by omega) h10
  exact chunk_11 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(290) ≤ S*`, `S*` the root of `pS` in `[17.5355339059, 17.5355339059]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((87677669529663688110021108552621225982121/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((87677669529663688110021109552621225982121/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 290 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

/-- `s(290) ≤ 14 + 5 * √2 / 2`: the side in closed form (`ExactQuad.packs_quad`). -/
theorem packs_closed : Packs 290 (14 + 5 * √2 / 2) := by
  have h := packs_quad (P := 14) (Q := (5/2 : ℚ)) (D := 2) (lo := (1414213562373095048801688724209/1000000000000000000000000000000 : ℚ)) (hi := (141421356237309504880168872421/100000000000000000000000000000 : ℚ)) packs (by decide +kernel)
  convert h using 1; push_cast; ring

theorem minSide_le_closed : minSide 290 ≤ 14 + 5 * √2 / 2 :=
  csInf_le ⟨0, fun _ hs => nonneg_of_packs_q (by norm_num) hs⟩ packs_closed

end UnitSquarePacking.EC.N290
