import Sqpack.Exact.Packs.N37.C0
import Sqpack.Exact.Packs.N37.C1

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 37, the certificate in `Data`, squares checked in 2 chunks. -/

namespace UnitSquarePacking.EC.N37

set_option maxHeartbeats 0

theorem ok (i : Fin 37) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  exact chunk_1 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(37) ≤ S*`, `S*` the root of `pS` in `[6.59861960924, 6.59861960924]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((6598619609244360116178370362678348804391/1000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((6598619609244360116178370562678348804391/1000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 37 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N37
