import Sqpack.Exact.Packs.N38.C0
import Sqpack.Exact.Packs.N38.C1

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 38, the certificate in `Data`, squares checked in 2 chunks. -/

namespace UnitSquarePacking.EC.N38

set_option maxHeartbeats 0

theorem ok (i : Fin 38) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  exact chunk_1 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(38) ≤ S*`, `S*` the root of `pS` in `[6.70710678119, 6.70710678119]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((4191941738241592202750527663815530649553/625000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((4191941738241592202750527788815530649553/625000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 38 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

/-- `s(38) ≤ 6 + √2 / 2`: the side in closed form (`ExactQuad.packs_quad`). -/
theorem packs_closed : Packs 38 (6 + √2 / 2) := by
  have h := packs_quad (P := 6) (Q := (1/2 : ℚ)) (D := 2) (lo := (1414213562373095048801688724209/1000000000000000000000000000000 : ℚ)) (hi := (141421356237309504880168872421/100000000000000000000000000000 : ℚ)) packs (by decide +kernel)
  convert h using 1; push_cast; ring

theorem minSide_le_closed : minSide 38 ≤ 6 + √2 / 2 :=
  csInf_le ⟨0, fun _ hs => nonneg_of_packs_q (by norm_num) hs⟩ packs_closed

end UnitSquarePacking.EC.N38
