import Sqpack.Exact.Packs.N4.C0

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 4, the certificate in `Data`, squares checked in 1 chunks. -/

namespace UnitSquarePacking.EC.N4

set_option maxHeartbeats 0

theorem ok (i : Fin 4) : boxOK cert i = true ∧ rowOK cert i = true := by
  exact chunk_0 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(4) ≤ S*`, `S*` the root of `pS` in `[2, 2]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((19999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((20000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 4 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N4
