import Sqpack.Exact.Packs.N42.C0
import Sqpack.Exact.Packs.N42.C1

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 42, the certificate in `Data`, squares checked in 2 chunks. -/

namespace UnitSquarePacking.EC.N42

set_option maxHeartbeats 0

theorem ok (i : Fin 42) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  exact chunk_1 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(42) ≤ S*`, `S*` the root of `pS` in `[7, 7]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((69999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((70000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 42 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N42
