import Sqpack.Exact.Packs.N50.C0
import Sqpack.Exact.Packs.N50.C1

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 50, the certificate in `Data`, squares checked in 2 chunks. -/

namespace UnitSquarePacking.EC.N50

set_option maxHeartbeats 0

theorem ok (i : Fin 50) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  exact chunk_1 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(50) ≤ S*`, `S*` the root of `pS` in `[7.57142857143, 7.57142857143]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((37857142857142857142857142357142857142857/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((37857142857142857142857143357142857142857/5000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 50 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N50
