import Sqpack.Exact.Packs.N53.C0
import Sqpack.Exact.Packs.N53.C1
import Sqpack.Exact.Packs.N53.C2

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 53, the certificate in `Data`, squares checked in 3 chunks. -/

namespace UnitSquarePacking.EC.N53

set_option maxHeartbeats 0

theorem ok (i : Fin 53) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  exact chunk_2 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(53) ≤ S*`, `S*` the root of `pS` in `[7.82287565553, 7.82287565553]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((78228756555322952952508077768196302128551/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((78228756555322952952508079768196302128551/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 53 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

/-- `s(53) ≤ 13 / 2 + √7 / 2`: the side in closed form (`ExactQuad.packs_quad`). -/
theorem packs_closed : Packs 53 (13 / 2 + √7 / 2) := by
  have h := packs_quad (P := (13/2 : ℚ)) (Q := (1/2 : ℚ)) (D := 7) (lo := (2645751311064590590501615753639/1000000000000000000000000000000 : ℚ)) (hi := (66143782776614764762540393841/25000000000000000000000000000 : ℚ)) packs (by decide +kernel)
  convert h using 1; push_cast; ring

theorem minSide_le_closed : minSide 53 ≤ 13 / 2 + √7 / 2 :=
  csInf_le ⟨0, fun _ hs => nonneg_of_packs_q (by norm_num) hs⟩ packs_closed

end UnitSquarePacking.EC.N53
