import Sqpack.Exact.Packs.N75.C0
import Sqpack.Exact.Packs.N75.C1
import Sqpack.Exact.Packs.N75.C2

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 75, the certificate in `Data`, squares checked in 3 chunks. -/

namespace UnitSquarePacking.EC.N75

set_option maxHeartbeats 0

theorem ok (i : Fin 75) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  exact chunk_2 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(75) ≤ S*`, `S*` the root of `pS` in `[9, 9]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((89999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((90000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 75 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N75
