import Sqpack.Exact.Packs.N9.C0

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 9, the certificate in `Data`, squares checked in 1 chunks. -/

namespace UnitSquarePacking.EC.N9

set_option maxHeartbeats 0

theorem ok (i : Fin 9) : boxOK cert i = true ∧ rowOK cert i = true := by
  exact chunk_0 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(9) ≤ S*`, `S*` the root of `pS` in `[3, 3]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((29999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((30000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 9 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N9
