import Sqpack.Exact.Packs.N90.C0
import Sqpack.Exact.Packs.N90.C1
import Sqpack.Exact.Packs.N90.C2
import Sqpack.Exact.Packs.N90.C3

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 90, the certificate in `Data`, squares checked in 4 chunks. -/

namespace UnitSquarePacking.EC.N90

set_option maxHeartbeats 0

theorem ok (i : Fin 90) : boxOK cert i = true ∧ rowOK cert i = true := by
  by_cases h0 : i.val < 25
  · exact chunk_0 i (by omega) h0
  by_cases h1 : i.val < 50
  · exact chunk_1 i (by omega) h1
  by_cases h2 : i.val < 75
  · exact chunk_2 i (by omega) h2
  exact chunk_3 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(90) ≤ S*`, `S*` the root of `pS` in `[10, 10]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((99999999999999999999999999/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((100000000000000000000000001/10000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 90 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N90
