#!/usr/bin/env python3
"""Leaf counts of the level-2 trees, up to the symmetries of the container.

Slots 0..7 in cyclic order round the boundary (the numbering of `level2_regions.classify`):
0 bottom-left, 1 bottom-right, 2 right-lower, 3 right-upper, 4 top-right, 5 top-left,
6 left-upper, 7 left-lower.  The D4 of the square acts on them as the subgroup of the octagon's
dihedral group generated by the shift by 2 (a 90-degree rotation) and the mirrors.
"""
import itertools

ROT = [2, 3, 4, 5, 6, 7, 0, 1]           # 90-degree rotation = shift by two slots
MIR = [1, 0, 7, 6, 5, 4, 3, 2]           # mirror in the vertical mid-line


def compose(a, b):
    return [a[b[i]] for i in range(len(a))]


def group(rot, mir):
    n = len(rot)
    g = list(range(n))
    S = [tuple(g)]
    for _ in range(n):
        g = compose(g, rot)
        if tuple(g) in S:
            break
        S.append(tuple(g))
    S = S + [tuple(compose(list(mir), list(g))) for g in S]
    return sorted(set(S))


def classes(alphabet, n, G, total_cap=None):
    seen = set()
    reps = []
    for p in itertools.product(alphabet, repeat=n):
        if p in seen:
            continue
        seen |= {tuple(p[g[i]] for i in range(n)) for g in G}
        reps.append(p)
    if total_cap is not None:
        reps = [p for p in reps if sum(p) <= total_cap]
    return reps


WALLS = ((0, 1), (2, 3), (4, 5), (6, 7))       # the two slots of each wall


def main():
    G8 = group(ROT, MIR)
    G4 = group([1, 2, 3, 0], [1, 0, 3, 2])
    print(f'slot group order {len(G8)}, strip group order {len(G4)}')
    for cap in (1, 2):
        r = classes(range(cap + 1), 8, G8)
        r8 = [p for p in r if sum(p) <= 8]
        print(f'per-slot counts 0..{cap}: {(cap+1)**8} patterns, {len(r)} classes, '
              f'{len(r8)} with total <= 8')
        if cap == 1:
            for p in r:
                print('   ', ''.join(map(str, p)), 'm =', sum(p))
    # the tree this note recommends: the chord lemma caps each wall strip at 3 centres, of which
    # two are the corner squares in the leaf k = 4, so at most one slot per wall is occupied
    r = [p for p in classes(range(2), 8, G8) if all(p[i] + p[j] <= 1 for i, j in WALLS)]
    seen = set()
    reps = []
    for p in itertools.product((0, 1), repeat=8):
        if any(p[i] + p[j] > 1 for i, j in WALLS) or p in seen:
            continue
        seen |= {tuple(p[g[i]] for i in range(8)) for g in G8}
        reps.append(p)
    print(f'per-slot 0/1 with at most one slot per wall (chord lemma, leaf k = 4): '
          f'{3**4} patterns, {len(reps)} classes')
    for p in sorted(reps, key=lambda q: (sum(q), q)):
        print('   ', ''.join(map(str, p)), 'm =', sum(p))
    for cap in (2, 3):
        r = classes(range(cap + 1), 4, G4)
        r8 = [p for p in r if sum(p) <= 8]
        print(f'per-strip counts 0..{cap}: {(cap+1)**4} patterns, {len(r)} classes, '
              f'{len(r8)} with total <= 8')
        for p in r8:
            print('   ', ''.join(map(str, p)), 'm =', sum(p))


if __name__ == '__main__':
    main()
