import Sqpack
#print axioms SquarePacking.wall_strip_le_three
#print axioms SquarePacking.wall_strip_le_three_of_packing
#print axioms SquarePacking.packing_le_weight_regions_choice
#print axioms SquarePacking.sum_assign_eq_sum_counts
-- zero-margin checker primitives (Sqpack/ZeroMargin.lean, search/RUNG2.md)
#print axioms SquarePacking.sq_subset_box_iff
#print axioms SquarePacking.mem_sq_of_corners
#print axioms SquarePacking.lemmaA
#print axioms SquarePacking.le_maxQuad
#print axioms SquarePacking.maxQuad_mem
#print axioms SquarePacking.mem_sq_iff_gval
#print axioms SquarePacking.gsum_le_corners
#print axioms SquarePacking.gsum_le_gmax
#print axioms SquarePacking.gmax_mem
#print axioms SquarePacking.lemmaG
#print axioms SquarePacking.lemmaG'
#print axioms SquarePacking.lemmaH
#print axioms SquarePacking.lemmaG_box
#print axioms SquarePacking.lemmaH_box
#print axioms SquarePacking.gval_le_of_gmax_sub
#print axioms SquarePacking.chain_regions_cover
#print axioms SquarePacking.chain_region_down
#print axioms SquarePacking.widU_strictMonoOn
#print axioms SquarePacking.adm_widU_le
#print axioms SquarePacking.clip_bin_no_loss
#print axioms SquarePacking.xnR_spec
#print axioms SquarePacking.xnW_spec
#print axioms SquarePacking.xnM_spec
#print axioms SquarePacking.condPoly_eq_gval
#print axioms SquarePacking.condPoly_nonpos_iff
#print axioms SquarePacking.condPoly_rect
#print axioms SquarePacking.qeval4_eq_bern
#print axioms SquarePacking.bern_le_max
#print axioms SquarePacking.qeval4_le_maxBern
#print axioms SquarePacking.bern_endpoints
#print axioms SquarePacking.polyOk_bern
#print axioms SquarePacking.polyOk_quad
-- D4 reduction (Sqpack/D4.lean, search/S32_EXACT.md §7, §11.3(d))
#print axioms SquarePacking.sq_add_pi_div_two
#print axioms SquarePacking.mem_sq_reflX
#print axioms SquarePacking.mem_sq_swapXY
#print axioms SquarePacking.capt_reflX
#print axioms SquarePacking.capt_swapXY
#print axioms SquarePacking.d4_reduce
#print axioms SquarePacking.d4_reduction
#print axioms SquarePacking.d4_reduction_u
-- weighted covers as integer data (Sqpack/Cover.lean)
#print axioms SquarePacking.sum_filter_coverA
#print axioms SquarePacking.sum_coverA
#print axioms SquarePacking.D4Inv_cover
#print axioms SquarePacking.PTree.mem_sound
#print axioms SquarePacking.PTree.nodup_of_chainB
-- s(32) = 6 (Sqpack/S32.lean, notes/lean-s32.md)
#print axioms SquarePacking.not_packs_of_cover
#print axioms SquarePacking.packs_grid
#print axioms SquarePacking.S32Data.check_ok
#print axioms SquarePacking.S32Data.wsum_tree
#print axioms SquarePacking.S32Data.card_entries
#print axioms SquarePacking.S32Data.total_lt
#print axioms SquarePacking.S32Data.d4Inv
#print axioms SquarePacking.S32CheckerCover.region
#print axioms SquarePacking.s32_cover_all
#print axioms SquarePacking.s32_not_packs
#print axioms SquarePacking.s32_packs
#print axioms SquarePacking.s32_isLeast
#print axioms SquarePacking.s32_eq_six
#print axioms SquarePacking.s32_eq_six_of_checker
