import Sqpack
#print axioms SquarePacking.wall_strip_le_three
#print axioms SquarePacking.wall_strip_le_three_of_packing
#print axioms SquarePacking.packing_le_weight_regions_choice
#print axioms SquarePacking.sum_assign_eq_sum_counts
-- zero-margin checker primitives (Sqpack/ZeroMargin.lean, search/RUNG2.md)
#print axioms SquarePacking.sq_subset_box_iff
#print axioms SquarePacking.mem_sq_of_corners
#print axioms SquarePacking.lemmaA
#print axioms SquarePacking.le_maxQuad
#print axioms SquarePacking.maxQuad_mem
#print axioms SquarePacking.mem_sq_iff_gval
#print axioms SquarePacking.gsum_le_corners
#print axioms SquarePacking.gsum_le_gmax
#print axioms SquarePacking.gmax_mem
#print axioms SquarePacking.lemmaG
#print axioms SquarePacking.lemmaG'
#print axioms SquarePacking.lemmaH
#print axioms SquarePacking.lemmaG_box
#print axioms SquarePacking.lemmaH_box
#print axioms SquarePacking.gval_le_of_gmax_sub
#print axioms SquarePacking.chain_regions_cover
#print axioms SquarePacking.chain_region_down
#print axioms SquarePacking.widU_strictMonoOn
#print axioms SquarePacking.adm_widU_le
#print axioms SquarePacking.clip_bin_no_loss
#print axioms SquarePacking.xnR_spec
#print axioms SquarePacking.xnW_spec
#print axioms SquarePacking.xnM_spec
#print axioms SquarePacking.condPoly_eq_gval
#print axioms SquarePacking.condPoly_nonpos_iff
#print axioms SquarePacking.condPoly_rect
#print axioms SquarePacking.qeval4_eq_bern
#print axioms SquarePacking.bern_le_max
#print axioms SquarePacking.qeval4_le_maxBern
#print axioms SquarePacking.bern_endpoints
#print axioms SquarePacking.polyOk_bern
#print axioms SquarePacking.polyOk_quad
