#!/usr/bin/env python3
"""Leaf counts of the full two-level tree (corner boxes + wall slots), up to the container's D4.

The regions are the thirteen of `notes/level2-design.md` 2.1 with `r = 1`: four corner boxes
`A_0..A_3` in cyclic order (bottom-left, bottom-right, top-right, top-left), eight wall slots
`W_0..W_7` in cyclic order (the numbering of `level2_regions.classify`), and the interior `I`.
They partition the container, so a leaf is a pair `(K, n)` with `K in {0,1}^4` the corner counts
and `n in {0,..,3}^8` the slot counts; the interior count is `12 - sum K - sum n`.

Constraints used, and where they come from (`notes/branch-semantics.md` 4, `notes/chord-lemma.md`):

* `K_j <= 1`: the admissible part `[1/2, r]^2` of a corner box has diameter `(2r-1)/sqrt2 < 1`
  for `(2r-1)^2 < 2` -- exact, and the check the verifier already performs.
* per wall `w` (slots `2w, 2w+1`, corner boxes `A_w, A_{w+1}`):
      n_{2w} + n_{2w+1} + K_{A_w} + K_{A_{w+1}} <= 3
  -- the chord lemma: at most three centres in the closed wall strip `[0,t] x [0,1]`.
* `sum K + sum n <= 12` (the interior count is non-negative).

`--slotcap 2` additionally caps a single slot at two centres, which is measured but *not* proved
(`level2-design.md` 2.3: three in one slot misses by -0.44 at `t = 3.98`); the default 3 uses only
the chord lemma and is the rigorous count.
"""
import argparse
import itertools

# slots 0..7 cyclic; ROT = 90 degrees = shift by two slots, MIR = mirror in the vertical mid-line
SLOT_ROT = [2, 3, 4, 5, 6, 7, 0, 1]
SLOT_MIR = [1, 0, 7, 6, 5, 4, 3, 2]
# corners in cyclic order A_0 = bottom-left, A_1 = bottom-right, A_2 = top-right, A_3 = top-left
CORN_ROT = [1, 2, 3, 0]
CORN_MIR = [1, 0, 3, 2]
# wall w owns slots (2w, 2w+1) and corner boxes (A_w, A_{w+1 mod 4})
WALLS = [((2 * w, 2 * w + 1), (w, (w + 1) % 4)) for w in range(4)]


def compose(a, b):
    return tuple(a[b[i]] for i in range(len(a)))


def group(rot, mir):
    """The order-8 group generated by rot and mir, as a list of permutations."""
    out, g = [], tuple(range(len(rot)))
    for _ in range(len(rot)):
        out.append(g)
        g = compose(tuple(rot), g)
        if g == tuple(range(len(rot))):
            break
    return sorted(set(out + [compose(tuple(mir), g) for g in out]))


def d4():
    """The eight elements of D4 as (slot permutation, corner permutation) pairs."""
    out, s, c = [], tuple(range(8)), tuple(range(4))
    for _ in range(4):
        out.append((s, c))
        out.append((compose(tuple(SLOT_MIR), s), compose(tuple(CORN_MIR), c)))
        s, c = compose(tuple(SLOT_ROT), s), compose(tuple(CORN_ROT), c)
    out = sorted(set(out))
    assert len(out) == 8 and len(group(SLOT_ROT, SLOT_MIR)) == 8
    # every element must carry walls to walls: the slot pair and the corner pair of a wall move
    # together (this is what makes the per-wall chord constraint D4-invariant)
    ws = {(frozenset(sl), frozenset(co)) for sl, co in WALLS}
    for gs, gc in out:
        for sl, co in WALLS:
            assert (frozenset(gs[i] for i in sl), frozenset(gc[j] for j in co)) in ws
    return out


def feasible(K, n, total=12):
    for slots, corners in WALLS:
        if n[slots[0]] + n[slots[1]] + K[corners[0]] + K[corners[1]] > 3:
            return False
    return sum(K) + sum(n) <= total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--slotcap', type=int, default=3, help='max centres in one slot (3 = chord lemma only)')
    ap.add_argument('--total', type=int, default=12)
    ap.add_argument('--list', action='store_true', help='list the leaves of each corner class')
    a = ap.parse_args()
    G = d4()
    seen, reps = set(), []
    for K in itertools.product((0, 1), repeat=4):
        for n in itertools.product(range(a.slotcap + 1), repeat=8):
            if (K, n) in seen or not feasible(K, n, a.total):
                continue
            seen |= {(compose(K, gc), compose(n, gs)) for gs, gc in G}
            reps.append((K, n))
    # group by the class of the corner pattern
    byk = {}
    for K, n in reps:
        key = min(compose(K, gc) for _, gc in G)
        byk.setdefault(key, []).append((K, n))
    print(f'slot cap {a.slotcap}, total <= {a.total}')
    print(f'{"corner leaf":>12}  {"k":>2}  {"slot leaves":>11}')
    tot = 0
    for key in sorted(byk, key=lambda p: (sum(p), p)):
        v = byk[key]
        tot += len(v)
        print(f'{"".join(map(str, key)):>12}  {sum(key):>2}  {len(v):>11}')
        if a.list:
            for K, n in sorted(v, key=lambda p: (sum(p[1]), p)):
                print(f'        K={"".join(map(str,K))} n={"".join(map(str,n))} '
                      f'interior={a.total - sum(K) - sum(n)}')
    print(f'{"TOTAL":>12}      {tot:>11}')


if __name__ == '__main__':
    main()
