#!/usr/bin/env python3
"""Sherali-Adams levels 2 (and 3) on the n = 11 extremal fractional-packing supports.

The exact analogue of `search/RANK8.md` section 4 (`rank8.py sa2`) for the 28-square
D4-symmetrised supports of `search/N11_ANATOMY.md`:

    python3 search/n11_sa2.py search/n11_exact_3.83375_support.txt search/n11_exact_3.85_support.txt

For each support file (`pose p q cx cy mass`, theta = 2 arctan(p/q), mass/8 on each dihedral image;
coincident images are merged and their masses summed) the script computes, with exact closed
geometry (touching counts as meeting; `leaf_ceiling.sq_meets_sq`, integer separating axes):

  alpha      maximum number of pairwise-disjoint squares (complete branch and bound)   [exact]
  point LP   max sum y_s  s.t.  sum_{s contains v} y_s <= 1 at every arrangement vertex v
  clique LP  max sum y_s  s.t.  sum_{s in K} y_s <= 1 for every maximal clique K (Bron-Kerbosch)
  SA-2       the level-2 Sherali-Adams lift of the point rows, and separately of the clique rows:
             variables y_s and y_{st} for closed-disjoint pairs only (y_{st} = 0, i.e. absent, for
             meeting pairs); rows y_{st} <= y_s, y_{st} <= y_t, y_s + y_t - y_{st} <= 1; and every
             base row  sum_{s in R} y_s <= 1  multiplied by x_u and by (1 - x_u):
                 sum_{s in R} y_{su} <= y_u          sum_{s in R} (y_s - y_{su}) <= 1 - y_u.
  SA-3       the level-3 lift of the same rows (triple variables for pairwise-disjoint triples only;
             base rows multiplied by every product of <= 2 literals, all products of <= 3 literals
             non-negative), unless it is too big (`--max-rows`).

The lifts are generated by one generic routine: a base row  sum_s a_s x_s <= b  times the literal
product  prod_{i in I} x_i prod_{j in J} (1 - x_j)  is linearised with  y_S = 0  whenever S contains
a meeting pair (x_i x_i = x_i, x_i (1 - x_i) = 0).  Every row is valid for the 0/1 points, so each
value is an upper bound on alpha; LP values are floats (HiGHS), alpha and the geometry are exact.

The dual multipliers of the lifted rows are aggregated by the REGION of the poses involved (corner
box [0,1]^2, wall strips, centre box -- `leaf_ceiling.region_boxes(t, 1)` on the centre, as in
N11_ANATOMY section 2), the way RANK8 section 4 tabulates dual mass by label pair.
"""
import argparse
import itertools
import os
import sys
import time
from fractions import Fraction as Fr

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import leaf_ceiling as lc                                             # noqa: E402

REPO = os.path.dirname(HERE)
_LOG = None


def log(msg=''):
    print(msg, flush=True)
    if _LOG:
        _LOG.write(str(msg) + '\n')
        _LOG.flush()


# ============================================================================ support -> squares
def load_support(path):
    """-> (t, squares, meta).  squares: distinct closed unit squares (coincident dihedral images
    merged, masses summed); meta[k] = dict(pose, mass (Fraction), region, theta_deg, cx, cy)."""
    t, sym, poses = lc.read_measure(path)
    sq, DM, pose_of = lc.build_squares(t, sym, poses)
    boxes = lc.region_boxes(t, 1)
    seen = {}
    squares, meta = [], []
    for s, k in zip(sq, pose_of):
        key = (tuple(sorted(s[6])), s[7])           # reduced corner coordinates: canonical
        if key in seen:
            i = seen[key]
            assert meta[i]['pose'] == k
            meta[i]['mass'] += Fr(s[8], DM)
            meta[i]['images'] += 1
            continue
        seen[key] = len(squares)
        squares.append(s)
        cx, cy = Fr(s[0], s[2]), Fr(s[1], s[2])
        regs = lc.regions_of(cx, cy, boxes)
        assert len(regs) == 1, (cx, cy, regs)
        reg = {'C': 'corner', 'W': 'wall', 'I': 'interior'}[regs[0][0]]
        th = np.degrees(np.arctan2(s[4], s[3]))                     # cos = a/r, sin = b/r
        meta.append(dict(pose=k, mass=Fr(s[8], DM), region=reg, label=regs[0], images=1,
                         theta=float(th), cx=cx, cy=cy))
    return t, squares, meta


def disjoint_matrix(squares):
    n = len(squares)
    dis = np.zeros((n, n), dtype=bool)
    for i in range(n):
        for j in range(i + 1, n):
            if not lc.sq_meets_sq(squares[i], squares[j]):
                dis[i, j] = dis[j, i] = True
    return dis


def alpha_bb(dis):
    """complete branch and bound for the maximum pairwise-disjoint subfamily (rank8.py sa2)"""
    n = len(dis)
    adj = [0] * n
    for i in range(n):
        for j in range(n):
            if dis[i, j]:
                adj[i] |= 1 << j
    best = [0, 0]

    def bb(cand, k, chosen):
        if bin(cand).count('1') + k <= best[0]:
            return
        if cand == 0:
            if k > best[0]:
                best[0], best[1] = k, chosen
            return
        c = cand
        while c:
            b = c & -c
            i = b.bit_length() - 1
            c ^= b
            bb(cand & adj[i] & ~((1 << (i + 1)) - 1), k + 1, chosen | b)
            cand ^= b
            if bin(cand).count('1') + k <= best[0]:
                return
    bb((1 << n) - 1, 0, 0)
    return best[0], [i for i in range(n) if best[1] >> i & 1]


def maximal_cliques(dis):
    """Bron-Kerbosch with pivoting on the MEETING graph (complement of `dis`)"""
    n = len(dis)
    nbr = [set(j for j in range(n) if j != i and not dis[i, j]) for i in range(n)]
    out = []

    def bk(R, P, X):
        if not P and not X:
            out.append(frozenset(R))
            return
        u = max(P | X, key=lambda v: len(P & nbr[v]))
        for v in list(P - nbr[u]):
            bk(R | {v}, P & nbr[v], X & nbr[v])
            P.remove(v)
            X.add(v)
    bk(set(), set(range(n)), set())
    return sorted(out, key=lambda K: (-len(K), sorted(K)))


def point_rows(squares, t):
    """distinct square-sets  {s : v in s}  over all arrangement vertices v (exact)"""
    V = lc.enumerate_vertices(squares, t, verbose=False)
    Inc = lc.incidences(squares, V, verbose=False)
    sets = {}
    for k, col in enumerate(Inc.cols):
        for v in col:
            sets.setdefault(int(v), set()).add(k)
    distinct = {frozenset(S) for S in sets.values()}
    return len(V), sorted(distinct, key=lambda S: (-len(S), sorted(S)))


def maximal_sets(rows):
    rows = sorted(set(rows), key=len, reverse=True)
    keep = []
    for S in rows:
        if not any(S < T for T in keep):
            keep.append(S)
    return keep


# ============================================================================ Sherali-Adams lift
class SA:
    """the level-k Sherali-Adams relaxation of  {sum_{s in R} x_s <= 1 for R in rows, x in [0,1]^n}
    with  y_S = 0  forced for every S containing a meeting pair (those variables are absent)."""

    def __init__(self, n, dis, rows, level):
        self.n, self.dis, self.level = n, dis, level
        self.var = {}                         # frozenset -> column
        for k in range(1, level + 1):
            for S in itertools.combinations(range(n), k):
                if all(dis[a, b] for a, b in itertools.combinations(S, 2)):
                    self.var[frozenset(S)] = len(self.var)
        self.nv = len(self.var)
        self.R, self.C, self.V, self.rhs, self.tag = [], [], [], [], []
        self.nrow = 0
        # base rows times every product of <= level-1 literals
        for ri, Rw in enumerate(rows):
            for I, J in self.literal_products(level - 1):
                self.add_row([(s, 1.0) for s in Rw], 1.0, I, J, ('row', ri, I, J))
        # every product of <= level literals is >= 0  (the pair/triple consistency rows);
        # products with J empty are plain bounds y_S >= 0 and are skipped
        for I, J in self.literal_products(level):
            if J:
                self.add_row([], 0.0, I, J, ('prod', None, I, J))
        import scipy.sparse as sp
        self.A = sp.coo_matrix((self.V, (self.R, self.C)), shape=(self.nrow, self.nv)).tocsr()
        self.b = np.array(self.rhs)

    def literal_products(self, kmax):
        """all (I, J) disjoint index tuples with 1 <= |I| + |J| <= kmax, plus (I, J) = ((), ())"""
        yield (), ()
        n = self.n
        for k in range(1, kmax + 1):
            for S in itertools.combinations(range(n), k):
                for m in range(k + 1):
                    for I in itertools.combinations(S, m):
                        J = tuple(x for x in S if x not in I)
                        yield I, J

    def lin(self, coef, I, J):
        """the linearisation of  (sum_s coef_s x_s + coef_None) * prod_I x_i prod_J (1 - x_j)
        as {column: value}; absent variables are zero."""
        out = {}
        for s, a in coef:
            if s in J:
                continue                                  # x_s (1 - x_s) = 0
            base = set(I) | ({s} if s is not None else set())
            for m in range(len(J) + 1):
                for T in itertools.combinations(J, m):
                    S = frozenset(base | set(T))
                    sign = -1.0 if m % 2 else 1.0
                    if not S:
                        out[-1] = out.get(-1, 0.0) + sign * a       # the constant 1
                    elif S in self.var:
                        c = self.var[S]
                        out[c] = out.get(c, 0.0) + sign * a
        return out

    def add_row(self, lhs, b, I, J, tag):
        """(lhs - b) * prod <= 0, i.e.  sum lhs_s x_s * prod  <=  b * prod"""
        d = self.lin([(s, a) for s, a in lhs] + [(None, -b)], I, J)
        const = d.pop(-1, 0.0)
        d = {c: v for c, v in d.items() if abs(v) > 1e-12}
        if not d:
            assert const <= 1e-12, (tag, const)
            return
        for c, v in d.items():
            self.R.append(self.nrow)
            self.C.append(c)
            self.V.append(v)
        self.rhs.append(-const)
        self.tag.append(tag)
        self.nrow += 1

    def solve(self):
        from scipy.optimize import linprog
        c = np.zeros(self.nv)
        for S, k in self.var.items():
            if len(S) == 1:
                c[k] = -1.0
        t0 = time.time()
        res = linprog(c, A_ub=self.A, b_ub=self.b, bounds=[(0, 1)] * self.nv, method='highs')
        assert res.status == 0, res.message
        self.wub = -np.asarray(res.upper.marginals)      # duals of the bounds y_S <= 1
        return -res.fun, res.x, -np.asarray(res.ineqlin.marginals), time.time() - t0


def plain_lp(n, rows):
    from scipy.optimize import linprog
    A = np.zeros((len(rows), n))
    for i, R in enumerate(rows):
        for s in R:
            A[i, s] = 1.0
    res = linprog(-np.ones(n), A_ub=A, b_ub=np.ones(len(rows)), bounds=[(0, 1)] * n,
                  method='highs')
    assert res.status == 0, res.message
    return -res.fun, res.x, -np.asarray(res.ineqlin.marginals)


# ============================================================================ exact certificate
def exact_certificate(sa, w, rows, meta, label, list_rows=True, maxden=10000):
    """Round the positive duals to rationals and verify EXACTLY (Fractions; every row coefficient
    is an integer) that  sum_k w_k * row_k  dominates the objective:  coefficient >= 1 on every
    y_s, >= 0 on every y_S with |S| >= 2, so  sum_s y_s <= sum_k w_k b_k  on the relaxation.
    Returns the exact bound or None."""
    pos = [k for k in range(sa.nrow) if w[k] > 1e-9]
    W = {k: Fr(float(w[k])).limit_denominator(maxden) for k in pos}
    A = sa.A.tocsr()
    acc = {}
    rhs = Fr(0)
    names = {c: S for S, c in sa.var.items()}
    ub = [(c, Fr(float(sa.wub[c])).limit_denominator(maxden)) for c in range(sa.nv)
          if sa.wub[c] > 1e-9]
    for c, v in ub:                                       # bound rows  y_S <= 1
        acc[c] = acc.get(c, Fr(0)) + v
        rhs += v
    for k in pos:
        lo, hi = A.indptr[k], A.indptr[k + 1]
        for c, v in zip(A.indices[lo:hi], A.data[lo:hi]):
            iv = int(round(v))
            assert abs(v - iv) < 1e-12
            acc[int(c)] = acc.get(int(c), Fr(0)) + W[k] * iv
        b = int(round(sa.b[k]))
        assert abs(sa.b[k] - b) < 1e-12
        rhs += W[k] * b
    ok = True
    for S, c in sa.var.items():
        need = 1 if len(S) == 1 else 0
        if acc.get(c, Fr(0)) < need:
            ok = False
            break
    if list_rows:
        log(f'  [{label}] the {len(pos)} rows + {len(ub)} bounds of the certificate (rational '
            f'duals, denominators <= {maxden}):')
        for c, v in sorted(ub, key=lambda cv: -cv[1]):
            S = sorted(names[c])
            log(f'    {str(v):>6s}  bound  y{"".join(f"_{x}" for x in S)} <= 1   '
                f'[{"".join(REG[meta[x]["region"]] for x in S)}]')
        for k in sorted(pos, key=lambda k: -w[k]):
            kind, ri, I, J = sa.tag[k]
            lo, hi = A.indptr[k], A.indptr[k + 1]
            terms = ' '.join(f'{"+" if v > 0 else "-"}y{"".join(f"_{x}" for x in sorted(names[int(c)]))}'
                             for c, v in zip(A.indices[lo:hi], A.data[lo:hi]))
            if kind == 'row':
                desc = (f'row {{{",".join(str(x) for x in sorted(rows[ri]))}}} [{signature(rows[ri], meta)}]'
                        + ''.join(f' * x_{u}[{REG[meta[u]["region"]]}]' for u in I)
                        + ''.join(f' * (1-x_{u})[{REG[meta[u]["region"]]}]' for u in J))
            else:
                desc = ('product' + ''.join(f' x_{u}[{REG[meta[u]["region"]]}]' for u in I)
                        + ''.join(f' (1-x_{u})[{REG[meta[u]["region"]]}]' for u in J) + ' >= 0')
            log(f'    {str(W[k]):>6s}  {desc}')
            log(f'            {terms} <= {int(round(sa.b[k]))}')
    if ok:
        log(f'  [{label}] EXACT: the rational combination proves  sum_s y_s <= {rhs} = {float(rhs):.9f} '
            f'on the relaxation (slack on y_s: {sorted({str(acc[sa.var[S]] - 1) for S in sa.var if len(S) == 1})})')
        return rhs
    log(f'  [{label}] rational rounding of the dual does NOT certify (float value only)')
    return None


# ============================================================================ dual aggregation
REG = {'corner': 'C', 'wall': 'W', 'interior': 'I'}


def signature(S, meta):
    c = {'C': 0, 'W': 0, 'I': 0}
    for s in S:
        c[REG[meta[s]['region']]] += 1
    return ''.join(f'{k}{v}' if v > 1 else k for k, v in c.items() if v)


def dual_tables(sa, w, rows, meta, label):
    """aggregate positive duals: (i) lifted base rows by (row signature, literal region),
    (ii) product rows by region multiset, (iii) pose-pair level: for a base row R lifted by u, the
    (region(s), region(u)) pairs over s in R disjoint from u, each getting w / #such s."""
    by_sig, by_prod, by_pair, base = {}, {}, {}, {}
    npos = 0
    for k, tag in enumerate(sa.tag):
        if w[k] <= 1e-9:
            continue
        npos += 1
        kind, ri, I, J = tag
        if kind == 'row':
            lits = tuple(I) + tuple(J)
            if not lits:
                key = signature(rows[ri], meta)
                base[key] = base.get(key, 0.0) + w[k]
                continue
            sig = signature(rows[ri], meta)
            lsig = ''.join(REG[meta[u]['region']] for u in lits)
            form = 'x' * len(I) + 'n' * len(J)            # n = (1 - x)
            key = (sig, lsig, form)
            by_sig[key] = by_sig.get(key, 0.0) + w[k]
            if len(lits) == 1:
                u = lits[0]
                part = [s for s in rows[ri] if sa.dis[s, u]]
                for s in part:
                    pk = tuple(sorted((REG[meta[s]['region']], REG[meta[u]['region']])))
                    by_pair[pk] = by_pair.get(pk, 0.0) + w[k] / len(part)
        else:
            lits = tuple(I) + tuple(J)
            key = (''.join(sorted(REG[meta[u]['region']] for u in lits)),
                   'x' * len(I) + 'n' * len(J))
            by_prod[key] = by_prod.get(key, 0.0) + w[k]
    log(f'\n  [{label}] {npos} of {sa.nrow} rows carry a positive dual (> 1e-9)')
    if base:
        log('  unlifted base rows by region signature of the row:')
        for key, v in sorted(base.items(), key=lambda kv: -kv[1]):
            log(f'    {v:10.6f}  row {key}')
    log('  lifted base rows by (row signature, literal regions, form: x = times x_u, n = times 1-x_u):')
    for key, v in sorted(by_sig.items(), key=lambda kv: -kv[1]):
        log(f'    {v:10.6f}  row {key[0]:8s} x literals {key[1]:3s} [{key[2]}]')
    log('  product rows (y_st <= y_s etc.) by region multiset and form:')
    for key, v in sorted(by_prod.items(), key=lambda kv: -kv[1]):
        log(f'    {v:10.6f}  {key[0]:4s} [{key[1]}]')
    if by_pair:
        log('  level-2 lifted rows spread over the (region(s), region(u)) pairs they couple '
            '(w / #s in R disjoint from u):')
        tot = sum(by_pair.values())
        for key, v in sorted(by_pair.items(), key=lambda kv: -kv[1]):
            log(f'    {v:10.6f}  ({key[0]},{key[1]})   {100 * v / tot:5.1f} %')
    return by_sig, by_prod, by_pair


# ============================================================================ main
def run(path, a):
    t0 = time.time()
    t, squares, meta = load_support(path)
    n = len(squares)
    mass = sum(m['mass'] for m in meta)
    log('=' * 100)
    log(f'{path}: t = {t} = {float(t):.6f}, {n} distinct closed unit squares, total mass {mass}')
    for reg in ('corner', 'wall', 'interior'):
        ks = [k for k in range(n) if meta[k]['region'] == reg]
        log(f'  {reg:9s}: {len(ks):2d} squares, mass {sum(meta[k]["mass"] for k in ks)}, '
            f'|theta| in {{{", ".join(sorted({f"{abs(meta[k]["theta"]):.3f}" for k in ks}))}}}')
    if a.legend:
        log('  square legend: index [region label] centre theta mass (#images merged)')
        for k, m in enumerate(meta):
            log(f'    {k:2d} [{m["label"]:2s}] ({float(m["cx"]):.5f}, {float(m["cy"]):.5f}) '
                f'theta {m["theta"]:8.4f}  mass {m["mass"]}  ({m["images"]})')
    dis = disjoint_matrix(squares)
    npairs = int(dis.sum() // 2)
    log(f'  closed-intersection graph: {n * (n - 1) // 2 - npairs} edges; {npairs} disjoint pairs')

    alpha, wit = alpha_bb(dis)
    log(f'  alpha = {alpha}  (complete branch and bound; witness squares {wit})')

    nV, prows_all = point_rows(squares, t)
    prows = maximal_sets(prows_all)
    plp_all, _, _ = plain_lp(n, prows_all)
    plp, y_p, _ = plain_lp(n, prows)
    log(f'  point rows: {nV} arrangement vertices -> {len(prows_all)} distinct square-sets, '
        f'{len(prows)} inclusion-maximal')
    log(f'  pure point LP = {plp_all:.9f} (all distinct sets), {plp:.9f} (maximal sets)')

    cl = maximal_cliques(dis)
    clp, y_c, _ = plain_lp(n, cl)
    sizes = {}
    for K in cl:
        sizes[len(K)] = sizes.get(len(K), 0) + 1
    helly = sum(1 for K in cl if K in set(prows_all))
    log(f'  maximal cliques: {len(cl)} (sizes {dict(sorted(sizes.items()))}); '
        f'{helly} of them are point rows (have a common point), {len(cl) - helly} are non-Helly')
    log(f'  clique LP = {clp:.9f}')

    results = dict(file=path, t=str(t), n=n, mass=str(mass), alpha=alpha, point_lp=plp,
                   clique_lp=clp, nverts=nV, npoint_rows=len(prows), ncliques=len(cl))
    tables = {}
    for name, rows in (('point', prows), ('clique', cl)):
        sa = SA(n, dis, rows, 2)
        val, y, w, dt = sa.solve()
        log(f'\n  SA-2 on {name} rows: {sa.nv} variables, {sa.nrow} rows -> {val:.9f}   '
            f'({dt:.1f} s)')
        results[f'sa2_{name}'] = val
        tables[name] = dual_tables(sa, w, rows, meta, f'SA-2 {name}')
        ex = exact_certificate(sa, w, rows, meta, f'SA-2 {name}', list_rows=a.list_rows)
        results[f'sa2_{name}_exact'] = str(ex) if ex is not None else None
        if a.print_y:
            log('  primal y_s: ' + ' '.join(f'{v:.4f}' for v in y[:n]))
    if a.level3:
        for name, rows in (('clique', cl), ('point', prows)):
            if name == 'point' and not a.level3_point:
                continue
            sa = SA(n, dis, rows, 3)
            log(f'\n  SA-3 on {name} rows: {sa.nv} variables, {sa.nrow} rows')
            if sa.nrow > a.max_rows:
                log(f'    skipped (> --max-rows {a.max_rows})')
                continue
            val, y, w, dt = sa.solve()
            log(f'  SA-3 on {name} rows -> {val:.9f}   ({dt:.1f} s)')
            results[f'sa3_{name}'] = val
            dual_tables(sa, w, rows, meta, f'SA-3 {name}')
            ex = exact_certificate(sa, w, rows, meta, f'SA-3 {name}', list_rows=False)
            results[f'sa3_{name}_exact'] = str(ex) if ex is not None else None
    results['time'] = time.time() - t0
    return results, tables


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('FILES', nargs='+')
    ap.add_argument('--log', default=os.path.join(REPO, 'runs', 'n11_sa2.log'))
    ap.add_argument('--no-level3', dest='level3', action='store_false')
    ap.add_argument('--level3-point', action='store_true',
                    help='also SA-3 on the point rows')
    ap.add_argument('--max-rows', type=int, default=2_000_000)
    ap.add_argument('--print-y', action='store_true')
    ap.add_argument('--no-legend', dest='legend', action='store_false')
    ap.add_argument('--no-list-rows', dest='list_rows', action='store_false',
                    help='do not print the SA-2 certificate rows explicitly')
    a = ap.parse_args()
    global _LOG
    os.makedirs(os.path.dirname(a.log), exist_ok=True)
    _LOG = open(a.log, 'w')
    log('# ' + ' '.join(sys.argv))
    allres = []
    for f in a.FILES:
        r, _ = run(f, a)
        allres.append(r)
    log('\n' + '=' * 100)
    log('SUMMARY  (alpha exact; every LP value is a float HiGHS optimum; "closes" = '
        '(LP - value) / (LP - alpha) with LP = the pure point LP)')
    hdr = f'{"support":40s} {"t":>10s} {"alpha":>5s} {"point LP":>12s} {"clique LP":>12s} ' \
          f'{"SA2 point":>12s} {"SA2 clique":>12s} {"SA3 clique":>12s} {"SA3 point":>12s}'
    log(hdr)
    for r in allres:
        gap = r['point_lp'] - r['alpha']

        def cell(k):
            if k not in r:
                return f'{"-":>12s}'
            return f'{r[k]:12.9f}'
        log(f'{os.path.basename(r["file"]):40s} {float(Fr(r["t"])):10.6f} {r["alpha"]:5d} '
            f'{cell("point_lp")} {cell("clique_lp")} {cell("sa2_point")} {cell("sa2_clique")} '
            f'{cell("sa3_clique")} {cell("sa3_point")}')
        closes = []
        for k in ('clique_lp', 'sa2_point', 'sa2_clique', 'sa3_clique', 'sa3_point'):
            if k in r:
                closes.append(f'{k}: {(r["point_lp"] - r[k]) / gap:.6f}')
        log(f'{"":40s} closes: ' + ', '.join(closes) + f'   ({r["time"]:.1f} s)')
        ex = [f'{k[:-6]}: {r[k]}' for k in ('sa2_point_exact', 'sa2_clique_exact',
                                             'sa3_clique_exact', 'sa3_point_exact') if r.get(k)]
        log(f'{"":40s} exact rational dual certificates: ' + ', '.join(ex))
    _LOG.close()


if __name__ == '__main__':
    main()
