#!/usr/bin/env python3
"""s2_insertable.py -- HEURISTIC float LP test of S2 (FRIEDMAN.md 9.4): is there an INSERTABLE valid closed cover of
[0,k]^2 with saving > c?  Write-up: search/S2_INSERTABLE.md.  Nothing here is a proof (float LP over sampled rows).

Insertable (FRIEDMAN.md 2.1): with t = (k-1-sqrt2)/2, mu restricted to the slab [t, t+1+sqrt2] x [0,k] is 1-periodic in
x (mu(A+e1) = mu(A) for A in [t, t+sqrt2] x [0,k]), and the same for the horizontal slab.  Mass bookkeeping:
p_x = mu([t,t+1) x [0,k]), p_y likewise, q = mu([t,t+1)^2); constraints p_x + p_y + q <= 2k+1 and q <= 1.

Model.  Atoms: points on the 1/1000 grid (lattice --col-pitch + --cols-from + priced on the 0.01 grid; none on the grid
lines or walls, as line_cover --no-line-points), segment pieces on the interior grid lines x, y in {1..k-1} (the 1/q
grid refined at the slab breakpoints t, t+sqrt2-1, t+1, t+sqrt2, t+2, t+1+sqrt2 -- a set closed under the +-1 shifts
inside the slab and under D4), and for class (b) Lebesgue squares [a, k-a]^2, a in {0, 0.05, ..} <= t (density = the
column value).  Baseline LP columns = D4 orbits of atoms.  Insertable LP = the same LP with the D4-orbit columns
aggregated into orbits of the group generated by D4 and the slab shifts (x_O equal on each class), i.e. A_ins = A G,
plus the two mass rows.  Both LPs always share the identical atom set and row set (one model).

Modes
  bookkeep            Lebesgue and qx2_data/L4_k02_box7.txt: periodicity, p, q, the inserted (k+1) box's total and a
                      float validity scan of it
  run TAG --k K ...   base(a) loop -> ins(a, mass 'sum') loop -> + Lebesgue squares -> ins(b, 'full') loop ->
                      [base(b) loop] -> final solves of every variant on the common final row set
  insert FILE.npz     insert a saved insertable cover once in x and y and float-scan the (k+1) box
"""
import sys, os, math, time, json, argparse, resource
for _v in ('OMP_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'MKL_NUM_THREADS'): os.environ.setdefault(_v, '1')
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import numpy as np
import scipy.sparse as sp
import multiprocessing as mp
import closed4 as C
import family_rows as F
import close_shifted as CS
import line_cover as LC
import mixed_cover as MC

SQ2 = math.sqrt(2.0)
EPS = 1e-9


# ============================================================================== geometry
def clip_area(cx, cy, th, x0, x1, y0, y1):
    """area of (closed unit square, centre (cx,cy), angle th) intersected with [x0,x1] x [y0,y1]; vectorised
    Sutherland-Hodgman (verified against mixed_cover.mass_in_square_float to 1e-11)."""
    cx = np.asarray(cx, float); cy = np.asarray(cy, float); th = np.broadcast_to(np.asarray(th, float), cx.shape)
    n = cx.size
    if n == 0: return np.zeros(0)
    c = np.cos(th).ravel(); s = np.sin(th).ravel(); cx = cx.ravel(); cy = cy.ravel()
    U = np.array([0.5, -0.5, -0.5, 0.5]); V = np.array([0.5, 0.5, -0.5, -0.5])
    X = cx[:, None] + c[:, None] * U[None] - s[:, None] * V[None]
    Y = cy[:, None] + s[:, None] * U[None] + c[:, None] * V[None]
    for (axis, val, sign) in ((0, x0, 1), (0, x1, -1), (1, y0, 1), (1, y1, -1)):
        Wc = X if axis == 0 else Y
        f = sign * (Wc - val)                                 # inside: f >= 0
        m = X.shape[1]
        X2 = np.empty((n, 2 * m)); Y2 = np.empty((n, 2 * m)); ok = np.zeros((n, 2 * m), bool)
        for i in range(m):
            j = (i + 1) % m
            fi, fj = f[:, i], f[:, j]
            X2[:, 2 * i] = X[:, i]; Y2[:, 2 * i] = Y[:, i]; ok[:, 2 * i] = fi >= 0
            cross = (fi >= 0) != (fj >= 0)
            den = np.where(cross, fi - fj, 1.0); lam = np.where(cross, fi / den, 0.0)
            X2[:, 2 * i + 1] = X[:, i] + lam * (X[:, j] - X[:, i]); Y2[:, 2 * i + 1] = Y[:, i] + lam * (Y[:, j] - Y[:, i])
            ok[:, 2 * i + 1] = cross
        o = np.argsort(~ok, axis=1, kind='stable'); cnt = ok.sum(1)
        X2 = np.take_along_axis(X2, o, 1); Y2 = np.take_along_axis(Y2, o, 1)
        last = np.maximum(cnt - 1, 0)
        pad = np.arange(2 * m)[None, :] >= cnt[:, None]
        X2 = np.where(pad, X2[np.arange(n), last][:, None], X2); Y2 = np.where(pad, Y2[np.arange(n), last][:, None], Y2)
        M = max(int(cnt.max()), 1)                            # (padding duplicates count as vertices: no fixed cap)
        X = X2[:, :M]; Y = Y2[:, :M]
        X[cnt == 0] = 0.0; Y[cnt == 0] = 0.0
    A = 0.5 * np.abs(np.sum(X * np.roll(Y, -1, 1) - np.roll(X, -1, 1) * Y, axis=1))
    return A


class Cover(LC.Cover):
    """line_cover.Cover plus rectangles of uniform density: rects (r,5) = [x0, x1, y0, y1, density]."""

    def __init__(self, s, P, w, segs=None, sw=None, rects=None):
        super().__init__(s, P, w, segs, sw)
        R = np.zeros((0, 5)) if rects is None else np.asarray(rects, float).reshape(-1, 5)
        self.rects = R[R[:, 4] > 0]

    def total(self):
        return super().total() + float(sum((r[1] - r[0]) * (r[3] - r[2]) * r[4] for r in self.rects))

    def rect_mass(self, cx, cy, th):
        out = np.zeros(np.shape(cx))
        if len(self.rects) == 0 or np.size(cx) == 0: return out
        th = np.broadcast_to(np.asarray(th, float), np.shape(cx))
        h = (np.abs(np.cos(th)) + np.abs(np.sin(th))) / 2
        for x0, x1, y0, y1, d in self.rects:
            inside = (cx - h >= x0) & (cx + h <= x1) & (cy - h >= y0) & (cy + h <= y1)
            outside = (cx + h <= x0) | (cx - h >= x1) | (cy + h <= y0) | (cy - h >= y1)
            part = ~(inside | outside)
            v = inside.astype(float)
            if part.any(): v[part] = clip_area(cx[part], cy[part], th[part], x0, x1, y0, y1)
            out += d * v
        return out

    def mass(self, poses, chunk=200000):
        out = super().mass(poses, chunk)
        poses = np.asarray(poses, float).reshape(-1, 3)
        if len(self.rects): out += self.rect_mass(poses[:, 0], poses[:, 1], poses[:, 2])
        return out

    def scan(self, th, pitch, sh=(0.0, 0.0), box=None):
        v, p = super().scan(th, pitch, sh, box)
        if len(v) and len(self.rects):
            v = v + self.rect_mass(p[:, 0], p[:, 1], np.full(len(p), th))
        return v, p


# ============================================================================== slab / group
class Slab:
    def __init__(self, k):
        self.k = int(k); t = (k - 1 - SQ2) / 2; self.t = t
        self.lo, self.hi = t, t + 1 + SQ2
        self.bps = [t, t + SQ2 - 1, t + 1, t + SQ2, t + 2, t + 1 + SQ2]

    def inside(self, v):
        return self.lo - EPS <= v <= self.hi + EPS


class Pieces:
    """the common piece grid of every line: 1/q grid refined at the slab breakpoints (if split)."""

    def __init__(self, k, q, slab, split=True):
        g = [j / q for j in range(k * q + 1)] + (slab.bps if split else [])
        g = sorted(g); gg = [g[0]]
        for v in g[1:]:
            if v - gg[-1] > 1e-9: gg.append(v)
        self.br = np.array(gg); self.t0 = self.br[:-1]; self.t1 = self.br[1:]; self.n = len(self.t0)
        key = {round(v * 1e7): i for i, v in enumerate(self.t0)}
        self.rev = np.array([key[round((k - b) * 1e7)] for b in self.t1])          # piece [k-t1, k-t0]
        self.shift = {}
        for d in (1, -1):
            self.shift[d] = np.array([key.get(round((a + d) * 1e7), -1) for a in self.t0])
        self.slab = slab

    def can_shift(self, i, d):
        s = self.slab; a, b = self.t0[i], self.t1[i]
        return s.inside(a) and s.inside(b) and s.inside(a + d) and s.inside(b + d) and self.shift[d][i] >= 0


def pt_gens(X, Y, KU, U, slab, ins):
    """neighbours of the point (X, Y) (integer coords, U units per 1.0) under the generators."""
    out = [(KU - X, Y), (Y, X)]
    if ins:
        x, y = X / U, Y / U
        for d in (1, -1):
            if slab.inside(x) and slab.inside(x + d): out.append((X + d * U, Y))
            if slab.inside(y) and slab.inside(y + d): out.append((X, Y + d * U))
    return out


def seg_gens(a, k, pcs, slab, ins):
    o, A, i = a
    out = [((0, k - A, i) if o == 0 else (1, A, int(pcs.rev[i]))), (1 - o, A, i)]
    if ins:
        for d in (1, -1):
            # x-shift (vertical slab): vertical line x = A moves; horizontal piece moves along its line
            if o == 0:
                if slab.inside(A) and slab.inside(A + d): out.append((0, A + d, i))
                if pcs.can_shift(i, d): out.append((0, A, int(pcs.shift[d][i])))          # y-shift of a vertical piece
            else:
                if pcs.can_shift(i, d): out.append((1, A, int(pcs.shift[d][i])))          # x-shift of a horizontal piece
                if slab.inside(A) and slab.inside(A + d): out.append((1, A + d, i))       # y-shift of the line y = A
    return out


def orbit(a0, gens):
    seen = {a0}; st = [a0]
    while st:
        a = st.pop()
        for b in gens(a):
            if b not in seen: seen.add(b); st.append(b)
    return seen


# ============================================================================== model
class Model:
    def __init__(self, k, q, D=1000, split=True):
        self.k = int(k); self.s = float(k); self.D = D; self.K = self.k * D
        self.slab = Slab(k); self.pcs = Pieces(self.k, q, self.slab, split); self.q = q
        self.sizes = []; self.kind = []; self.gkey = []; self.keys = {}
        self.P = np.zeros((0, 2)); self.own = np.zeros(0, np.int64)
        self.S = np.zeros((0, 4)); self.sown = np.zeros(0, np.int64)
        self.Lcols = []                                  # (a, col)
        self.rows = []; self.rkey = set(); self.R = []; self.C = []; self.V = []; self.perm = []
        self.mx = []                                     # per column (px, py, q)

    # ------------------------------------------------------------ columns
    def _new_col(self, kind, size, gkey, m3):
        c = len(self.sizes); self.sizes.append(float(size)); self.kind.append(kind); self.gkey.append(gkey); self.mx.append(m3)
        return c

    def strip_masses_pts(self, pts):
        t = self.slab.t; x = pts[:, 0]; y = pts[:, 1]
        ix = (x >= t) & (x < t + 1); iy = (y >= t) & (y < t + 1)
        return (float(ix.sum()), float(iy.sum()), float((ix & iy).sum()))

    def strip_masses_segs(self, segs):
        t = self.slab.t; px = py = qq = 0.0
        for o, a, t0, t1 in segs:
            mid = (t0 + t1) / 2
            ina = t <= a < t + 1; inm = t <= mid < t + 1
            if o == 0: px += ina; py += inm
            else: py += ina; px += inm
            qq += ina and inm
        return (px, py, qq)

    def add_point_closed(self, X, Y):
        """add the insertable orbit of (X, Y) as D4-orbit columns (one group). returns #new columns."""
        sl = self.slab; KU = self.K; U = self.D
        X = min(max(int(X), 0), KU); Y = min(max(int(Y), 0), KU)
        if ('p', X, Y) in self.keys: return 0
        full = orbit((X, Y), lambda a: pt_gens(a[0], a[1], KU, U, sl, True))
        gk = ('p', min(full)); n = 0; done = set()
        for a in sorted(full):
            if a in done: continue
            d4 = orbit(a, lambda b: pt_gens(b[0], b[1], KU, U, sl, False)); done |= d4
            P = np.array(sorted(d4), float) / U
            c = self._new_col('p', len(d4), gk, self.strip_masses_pts(P))
            for b in d4: self.keys[('p',) + b] = c
            self.P = np.concatenate([self.P, P]); self.own = np.concatenate([self.own, np.full(len(P), c)])
            if self.rows: self._col_block(c, P, None)
            n += 1
        return n

    def add_segments(self, lines):
        k = self.k; pcs = self.pcs; sl = self.slab; n = 0
        for A in lines:
            for i in range(pcs.n):
                a0 = (0, A, i)
                if ('s',) + a0 in self.keys: continue
                full = orbit(a0, lambda a: seg_gens(a, k, pcs, sl, True)); gk = ('s', min(full)); done = set()
                for a in sorted(full):
                    if a in done: continue
                    d4 = orbit(a, lambda b: seg_gens(b, k, pcs, sl, False)); done |= d4
                    S = np.array([(o, AA, pcs.t0[j], pcs.t1[j]) for (o, AA, j) in sorted(d4)], float)
                    c = self._new_col('s', len(d4), gk, self.strip_masses_segs(S))
                    for b in d4: self.keys[('s',) + b] = c
                    self.S = np.concatenate([self.S, S]); self.sown = np.concatenate([self.sown, np.full(len(S), c)])
                    if self.rows: self._col_block(c, None, S)
                    n += 1
        return n

    def add_lebesgue(self, avals):
        k = self.k; n = 0
        for a in avals:
            if ('L', round(a, 6)) in self.keys: continue
            L = k - 2 * a
            c = self._new_col('L', L * L, ('L', round(a, 6)), (L, L, 1.0)); self.keys[('L', round(a, 6))] = c
            self.Lcols.append((a, c))
            if self.rows: self._col_block(c, None, None, a)
            n += 1
        return n

    # ------------------------------------------------------------ coefficients
    def _leb_coef(self, Q, a, c):
        k = self.k
        cov = Cover(k, np.zeros((0, 2)), np.zeros(0), rects=[(a, k - a, a, k - a, 1.0)])
        v = cov.rect_mass(Q[:, 0], Q[:, 1], Q[:, 2]); nz = np.nonzero(v > 1e-14)[0]
        return nz, np.full(len(nz), c), v[nz]

    def _col_block(self, c, P, S, a=None):
        Q = np.array(self.rows)
        if P is not None: r, cc, v = LC.MixedModel._pt_coef(Q, P, np.full(len(P), c))
        elif S is not None: r, cc, v = LC.MixedModel._seg_coef(Q, S, np.full(len(S), c))
        else: r, cc, v = self._leb_coef(Q, a, c)
        if len(r): self.R.append(np.asarray(r, np.int64)); self.C.append(np.asarray(cc, np.int64)); self.V.append(np.asarray(v, float))

    def canon(self, cx, cy, th):
        s = self.s
        imgs = [(cx, cy), (s - cy, cx), (s - cx, s - cy), (cy, s - cx)]
        a, b = min((round(x, 7), round(y, 7)) for x, y in imgs)
        return (a, b, round(th, 9))

    def add_rows(self, poses, perm=False):
        new = []
        for cx, cy, th in np.asarray(poses, float).reshape(-1, 3):
            key = self.canon(cx, cy, th)
            if key in self.rkey: continue
            self.rkey.add(key); new.append((float(cx), float(cy), float(th)))
        if not new: return 0
        r0 = len(self.rows); self.rows.extend(new); self.perm.extend([perm] * len(new)); Q = np.array(new)
        blocks = []
        if len(self.P): blocks.append(LC.MixedModel._pt_coef(Q, self.P, self.own))
        if len(self.S): blocks.append(LC.MixedModel._seg_coef(Q, self.S, self.sown))
        for a, c in self.Lcols: blocks.append(self._leb_coef(Q, a, c))
        for r, cc, v in blocks:
            if len(r): self.R.append(np.asarray(r, np.int64) + r0); self.C.append(np.asarray(cc, np.int64)); self.V.append(np.asarray(v, float))
        return len(new)

    def matrix(self):
        nr, nc = len(self.rows), len(self.sizes)
        if not self.R: return sp.csr_matrix((nr, nc))
        return sp.coo_matrix((np.concatenate(self.V), (np.concatenate(self.R), np.concatenate(self.C))), shape=(nr, nc)).tocsr()

    def prune(self, keep):
        keep = np.asarray(keep, bool) | np.array(self.perm, bool)
        idx = np.full(len(self.rows), -1, np.int64); idx[np.nonzero(keep)[0]] = np.arange(int(keep.sum()))
        R = np.concatenate(self.R); Cc = np.concatenate(self.C); V = np.concatenate(self.V)
        nr = idx[R]; sel = nr >= 0
        self.R = [nr[sel]]; self.C = [Cc[sel]]; self.V = [V[sel]]
        self.rows = [rw for rw, kk in zip(self.rows, keep) if kk]; self.perm = [p for p, kk in zip(self.perm, keep) if kk]
        self.rkey = set(self.canon(*rw) for rw in self.rows)

    # ------------------------------------------------------------ groups / LP
    def grouping(self, mode, allowed=None):
        """G (ncols x ngroups) 0/1: mode 'base' = identity, 'ins' = insertable classes.  allowed: column mask."""
        nc = len(self.sizes)
        al = np.ones(nc, bool) if allowed is None else allowed
        if mode == 'base': keys = [(i,) for i in range(nc)]
        else: keys = self.gkey
        gid = {}; rows = []; cols = []
        for i in range(nc):
            if not al[i]: continue
            g = gid.setdefault(keys[i], len(gid)); rows.append(i); cols.append(g)
        return sp.csr_matrix((np.ones(len(rows)), (rows, cols)), shape=(nc, len(gid)))

    def crossing_mask(self):
        """True for columns whose atoms lie in the closed crossing square [t, t+1+sqrt2]^2 (D4-invariant, and the
        slab shifts keep it), False otherwise; Lebesgue columns False."""
        lo, hi = self.slab.lo - EPS, self.slab.hi + EPS; nc = len(self.sizes); out = np.zeros(nc, bool)
        inP = (self.P[:, 0] >= lo) & (self.P[:, 0] <= hi) & (self.P[:, 1] >= lo) & (self.P[:, 1] <= hi)
        out[self.own[inP]] = True
        S = self.S
        inS = (S[:, 1] >= lo) & (S[:, 1] <= hi) & (S[:, 2] >= lo) & (S[:, 3] <= hi)
        out[self.sown[inS]] = True
        return out

    def solve(self, mode, mass='none', allowed=None, ipm=True):
        """mass: 'none'; 'sum' (p_x + p_y + q <= 2k+1: one insertion step keeps the saving); 'full' (and q <= 1)."""
        import highspy
        A0 = self.matrix(); G = self.grouping(mode, allowed)
        A = (A0 @ G).tocsr(); nr, ng = A.shape
        cost = G.T @ np.array(self.sizes)
        M3 = np.array(self.mx); MX = G.T @ M3                       # (ng, 3) px, py, q per unit group value
        inf = highspy.kHighsInf
        h = highspy.Highs(); h.setOptionValue('output_flag', False); h.setOptionValue('random_seed', 0)
        if ipm: h.setOptionValue('solver', 'ipm'); h.setOptionValue('run_crossover', 'off')
        h.addVars(ng, np.zeros(ng), np.full(ng, inf)); h.changeColsCost(ng, np.arange(ng, dtype=np.int32), cost)
        A.sort_indices()
        h.addRows(nr, np.ones(nr), np.full(nr, inf), int(A.nnz), A.indptr[:-1].astype(np.int32), A.indices.astype(np.int32), A.data.astype(float))
        nm = 0
        if mass in ('sum', 'full'):
            k = self.k
            for coef, ub in ((MX[:, 0] + MX[:, 1] + MX[:, 2], 2 * k + 1), (MX[:, 2], 1.0))[:1 if mass == 'sum' else 2]:
                nz = np.nonzero(np.abs(coef) > 0)[0]
                h.addRow(-inf, ub, len(nz), nz.astype(np.int32), coef[nz].astype(float)); nm += 1
        h.run()
        st = h.getModelStatus()
        if st != highspy.HighsModelStatus.kOptimal and ipm:          # retry with dual simplex (IPM w/o crossover)
            h.setOptionValue('solver', 'simplex'); h.clearSolver(); h.run(); st = h.getModelStatus()
        if st != highspy.HighsModelStatus.kOptimal:
            self.last_status = h.modelStatusToString(st); return None
        sol = h.getSolution(); xg = np.maximum(np.array(sol.col_value), 0.0)
        yall = np.array(sol.row_dual); y = np.maximum(yall[:nr], 0.0)
        if ipm: xg[xg < 1e-10] = 0.0; y[y < 1e-10] = 0.0
        x = G @ xg
        px, py, qq = (M3.T @ x)
        return dict(val=float(cost @ xg), x=x, y=y, Ax=A0 @ x, px=float(px), py=float(py), q=float(qq),
                    mdual=[float(v) for v in yall[nr:]], ng=ng)

    def cover(self, x):
        rects = [(a, self.k - a, a, self.k - a, x[c]) for a, c in self.Lcols if x[c] > 0]
        return Cover(self.s, self.P, x[self.own] if len(self.own) else np.zeros(0), self.S,
                     x[self.sown] if len(self.sown) else np.zeros(0), rects)

    def save(self, path, sol, note=''):
        x = sol['x']
        np.savez_compressed(path, k=self.k, P=self.P, w=x[self.own] if len(self.own) else np.zeros(0), S=self.S,
                            sw=x[self.sown] if len(self.sown) else np.zeros(0),
                            rects=np.array([(a, self.k - a, a, self.k - a, x[c]) for a, c in self.Lcols]).reshape(-1, 5),
                            val=sol['val'], note=note)


# ============================================================================== pricing
def symcov_grid(m, y, pitch=0.01, ysup=1e-9):
    """D4-symmetrised closed-square coverage of the dual on the full pitch grid (as closed4.price)."""
    Q = np.array(m.rows[:len(y)])[y > ysup]; yy = y[y > ysup]; s = m.s          # rows added after the solve: not priced
    n0 = int(round(s / pitch)); Dg = np.zeros((n0 + 1, n0 + 1))
    if len(yy) == 0: return Dg
    cx0, cy0, t0 = Q[:, 0], Q[:, 1], Q[:, 2]
    imgs = [(cx0, cy0, t0), (s - cx0, cy0, -t0), (cx0, s - cy0, -t0), (s - cx0, s - cy0, t0),
            (cy0, cx0, -t0), (s - cy0, cx0, t0), (cy0, s - cx0, t0), (s - cy0, s - cx0, -t0)]
    R = np.concatenate([np.c_[a * np.cos(th) + b * np.sin(th), -a * np.sin(th) + b * np.cos(th), np.cos(th), np.sin(th), yy / 8.0]
                        for a, b, th in imgs])
    I, J = np.meshgrid(np.arange(n0 + 1), np.arange(n0 + 1), indexing='ij'); I = I.ravel(); J = J.ravel()
    sel = (I <= J) & (2 * J <= n0); I = I[sel]; J = J[sel]; G = np.c_[I, J] * pitch
    out = np.zeros(len(G))
    for i in range(0, len(R), 2000):
        B = R[i:i + 2000]
        q0 = G[:, 0:1] * B[:, 2] + G[:, 1:2] * B[:, 3]; q1 = -G[:, 0:1] * B[:, 3] + G[:, 1:2] * B[:, 2]
        ins = np.maximum(np.abs(q0 - B[:, 0]), np.abs(q1 - B[:, 1])) <= 0.5 + C.TOL
        out += ins @ B[:, 4]
    for a, b in ((I, J), (n0 - I, J), (I, n0 - J), (n0 - I, n0 - J), (J, I), (n0 - J, I), (J, n0 - I), (n0 - J, n0 - I)):
        Dg[a, b] = out
    return Dg


def price(m, y, mode, pitch=0.01, want=150):
    """returns candidate grid points (X, Y) on the 1/D grid whose column (mode 'base': D4 orbit; 'ins': insertable
    orbit) has negative reduced cost on the coverage duals, best mean coverage first."""
    Dg = symcov_grid(m, y, pitch); n0 = Dg.shape[0] - 1; U = int(round(1 / pitch)); sl = m.slab
    I, J = np.nonzero(Dg > 1 + 1e-7)
    cand = []; seen = set()
    for i, j in zip(I, J):
        if not (i <= j and 2 * j <= n0): continue
        if i % U == 0 or j % U == 0: continue                  # no points on grid lines / walls
        if mode == 'base':
            cand.append((Dg[i, j], i, j))
        else:
            orb = orbit((int(i), int(j)), lambda a: pt_gens(a[0], a[1], n0, U, sl, True))
            key = min(orb)
            if key in seen: continue
            seen.add(key)
            vals = np.array([Dg[a, b] for a, b in orb])
            if np.sum(1 - vals) < -1e-7: cand.append((float(vals.mean()), i, j))
    cand.sort(reverse=True)
    r = int(round(m.D * pitch))
    return [(c, i * r, j * r) for c, i, j in cand[:want]]


# ============================================================================== loop pieces
def cut_round(m, cov, pool, rng, thetas, Ax, nproc, perang=150, add=True):
    """phase-A cutting planes (line_cover recipe): 0.01 lattice with a random shift, polish of the worst + tight rows,
    near-tile and item-3 families.  Returns stats and (if add) the number of new rows."""
    s = m.s
    outs = pool.map(LC._sep, [(cov, th, 0.01, tuple(rng.random(2)), perang, 0.05, 1 - 1e-9) for th in thetas])
    Lp = np.concatenate([o[0] for o in outs]); Lv = np.concatenate([o[1] for o in outs]); gmin = min(o[2] for o in outs)
    rws = np.array(m.rows)
    tight = rws[np.argsort(Ax)[:200]] if Ax is not None and len(Ax) == len(rws) else np.zeros((0, 3))
    seeds = np.r_[Lp[np.argsort(Lv)[:400]], tight]
    res = pool.map(LC._pol, [(cov, ch, int(rng.integers(1 << 30))) for ch in np.array_split(seeds, 2 * nproc)])
    fp = np.concatenate([q[0] for q in res]); fv = np.concatenate([q[1] for q in res])
    pmin = min([float(q[3].min()) for q in res if len(q[3])] + [9.0])
    fp = fp[np.argsort(fv)[:3000]]
    tq = LC.tile_poses(s, 0.002, 0.01, [0.0, 1e-5, 1e-3, 0.01, 0.03, 0.1, 0.2, 0.4, 0.7, 1.0, 1.5])
    tv = np.concatenate(pool.map(LC._mass, [(cov, ch) for ch in np.array_split(tq, 2 * nproc)]))
    tb = tq[tv < 1 - 1e-9]; tb = tb[np.argsort(tv[tv < 1 - 1e-9])[:1000]]
    FQ = np.array(F.item3(s, 0.002, [0.0, 1e-6, 1e-4, 1e-3, 1e-2, 10 ** -1.5]))
    fqv = np.concatenate(pool.map(LC._mass, [(cov, ch) for ch in np.array_split(FQ, 2 * nproc)]))
    fb = FQ[fqv < 1 - 1e-9]; fb = fb[np.argsort(fqv[fqv < 1 - 1e-9])[:1000]]
    st = dict(lat=float(gmin), pol=float(pmin), tile=float(tv.min()), fam=float(fqv.min()))
    st['min'] = min(st.values())
    n = 0
    if add: n = m.add_rows(Lp) + m.add_rows(fp) + m.add_rows(tb) + m.add_rows(fb)
    return st, n


def cpu_now():
    a = resource.getrusage(resource.RUSAGE_SELF); b = resource.getrusage(resource.RUSAGE_CHILDREN)
    return a.ru_utime + a.ru_stime + b.ru_utime + b.ru_stime


# ============================================================================== run
def run(a):
    os.makedirs('runs', exist_ok=True)
    tag = f"s2_{a.tag}"; lf = open(f"runs/{tag}.log", 'a'); T0 = time.time()

    def log(msg):
        msg = f"[{time.time() - T0:7.0f}s] {msg}"; print(msg, flush=True); lf.write(msg + '\n'); lf.flush()
    log(f"s2_insertable.py run {' '.join(sys.argv[2:])}  pid {os.getpid()}  {time.strftime('%F %T')}")
    k = a.k; rng = np.random.default_rng(a.seed)
    m = Model(k, a.q, split=not a.no_split)
    sl = m.slab
    log(f"k = {k}, t = {sl.t:.6f}, slab [{sl.lo:.6f}, {sl.hi:.6f}], pieces per line {m.pcs.n} (q = {a.q})")
    # ---- columns
    nseg = m.add_segments(list(range(1, k)))
    npt = 0
    for x, y in C.column_lattice(float(k), a.col_pitch):
        X, Y = int(round(x * 1000)), int(round(y * 1000))
        if X % 1000 == 0 or Y % 1000 == 0: continue
        npt += m.add_point_closed(X, Y)
    for f in (a.cols_from or '').split(','):
        if not f.strip(): continue
        cv = MC.load(f.strip())
        for X, Y, _ in cv['points']:
            X = int(round(X * 1000 / cv['D'])); Y = int(round(Y * 1000 / cv['D']))
            if X % 1000 == 0 or Y % 1000 == 0: continue
            npt += m.add_point_closed(X, Y)
    ng_ins = m.grouping('ins').shape[1]
    log(f"columns: {nseg} segment D4-orbits ({len(m.S)} pieces), {npt} point D4-orbits ({len(m.P)} atoms); "
        f"{len(m.sizes)} base columns, {ng_ins} insertable classes")
    pool = mp.get_context('fork').Pool(a.nproc)
    thetas = [math.radians(d) for d in C.angle_list(a.deg_step)]
    # ---- initial rows
    if a.warm:
        cov0 = LC.cover_from_file(a.warm)[0]
        outs = pool.map(LC._sep, [(cov0, th, 0.01, (0.0, 0.0), a.warm_perang, 0.03, 1.005) for th in thetas])
        n0 = m.add_rows(np.concatenate([o[0] for o in outs]))
        log(f"warm rows from {a.warm} (total {cov0.total():.6f}): {n0}")
    else:
        cov0 = Cover(float(k), np.zeros((0, 2)), np.zeros(0))
        outs = pool.map(LC._sep, [(cov0, th, 0.05, (0.0, 0.0), 150, 0.05, 1.005) for th in thetas])
        m.add_rows(np.concatenate([o[0] for o in outs]))
    for f in (a.rows_from or '').split(','):
        if f.strip(): log(f"rows from {f}: {m.add_rows(C.read_poses(f.strip(), float(k)), perm=True)}")
    m.add_rows(LC.tile_poses(float(k), 0.004, 0.012, [0.0, 1e-4, 0.01, 0.03, 0.1, 0.3, 1.0]))
    if a.germ:
        G = LC.germ_poses(float(k), a.q, 1e-5, 1); ng = m.add_rows(G, perm=True)
        log(f"germ family (q = {a.q}): {len(G)} poses, {ng} new permanent rows")
    log(f"initial rows: {len(m.rows)}")
    last = {}
    results = {}

    def loop(name, mode, mass, allowed, rounds):
        hist = []; prev = None
        for r in range(rounds):
            tl = time.time(); sol = m.solve(mode, mass=mass, allowed=allowed()); tlp = time.time() - tl
            if sol is None: log(f"[{name}] LP failed: {m.last_status}"); return hist
            last[name] = sol
            cov = m.cover(sol['x'])
            stt, nr = cut_round(m, cov, pool, rng, thetas, sol['Ax'], a.nproc)
            nc = 0
            if not a.no_colgen:
                for _, X, Y in price(m, sol['y'], mode, 0.01, a.cg_want): nc += m.add_point_closed(X, Y)
            rec = dict(round=r, LP=sol['val'], px=sol['px'], py=sol['py'], q=sol['q'], mdual=sol['mdual'], rows=len(m.rows),
                       cols=len(m.sizes), ng=sol['ng'], **stt, newrows=nr, newcols=nc, t_lp=round(tlp))
            hist.append(rec)
            log(f"[{name}] r{r} LP={sol['val']:.6f} saving {k * k - sol['val']:.4f} | px {sol['px']:.4f} py {sol['py']:.4f} q {sol['q']:.4f} "
                f"mdual {['%.4f' % v for v in sol['mdual']]} | lat {stt['lat']:.5f} pol {stt['pol']:.5f} tile {stt['tile']:.5f} "
                f"fam {stt['fam']:.5f} | +{nr} rows +{nc} cols -> rows {len(m.rows)} cols {len(m.sizes)} ({sol['ng']} vars) | lp {tlp:.0f}s cpu {cpu_now():.0f}s")
            if prev is not None and abs(sol['val'] - prev) < a.tol * sol['val'] and r >= a.min_rounds - 1 and stt['min'] > 1 - a.viol_tol:
                break
            if nr == 0 and nc == 0: break
            prev = sol['val']
            maybe_prune()
        return hist

    def maybe_prune():
        if a.prune_at and len(m.rows) > a.prune_at:
            nr = len(m.rows); keep = np.zeros(nr, bool)
            for sol in last.values():
                n_ = min(len(sol['y']), nr)
                keep[:n_] |= (sol['y'][:n_] > 1e-8) | (sol['Ax'][:n_] <= 1 + a.prune_slack)
                keep[n_:] = True
            keep[-a.prune_keep:] = True
            m.prune(keep); log(f"   pruned {nr} -> {len(m.rows)} rows")
            last.clear()

    noL = lambda: np.array([kd != 'L' for kd in m.kind])
    allc = lambda: None
    noX = lambda: ~m.crossing_mask()                  # crossing square atoms dropped (exact when q <= 1: S2_INSERTABLE.md sec 2)
    noLX = lambda: noL() & ~m.crossing_mask()

    def final(configs):
        for nm, mode, mass, allowed, resid in configs:
            tl = time.time(); sol = m.solve(mode, mass=mass, allowed=allowed())
            if sol is None:
                results[nm] = dict(status=m.last_status, rows=len(m.rows)); log(f"FINAL {nm}: LP status {m.last_status}"); continue
            cov = m.cover(sol['x'])
            stt = cut_round(m, cov, pool, rng, thetas, sol['Ax'], a.nproc, add=False)[0] if resid else {}
            o = results[nm] = dict(LP=sol['val'], saving=k * k - sol['val'], px=sol['px'], py=sol['py'], q=sol['q'], mdual=sol['mdual'],
                                   resid=stt, t=round(time.time() - tl), segw=float(cov.sw.sum()), ptw=float(cov.w.sum()),
                                   lebw=float(cov.total() - cov.sw.sum() - cov.w.sum()), rows=len(m.rows), vars=sol['ng'])
            m.save(f"runs/{tag}_{nm}.npz", sol, nm)
            log(f"FINAL {nm}: LP {o['LP']:.6f} saving {o['saving']:.4f} (pts {o['ptw']:.3f} segs {o['segw']:.3f} leb {o['lebw']:.3f}) "
                f"px {o['px']:.4f} py {o['py']:.4f} q {o['q']:.4f} px+py+q {o['px'] + o['py'] + o['q']:.4f} mdual {o['mdual']} | "
                + (f"resid lat {stt['lat']:.5f} pol {stt['pol']:.5f} tile {stt['tile']:.5f} fam {stt['fam']:.5f} | " if resid else '')
                + f"rows {len(m.rows)} vars {sol['ng']} | {o['t']}s cpu {cpu_now():.0f}s")
            json.dump(dict(args=vars(a), results=results, hist=H, cpu=cpu_now()), open(f"runs/{tag}.json", 'w'), indent=1)

    H = {}
    if a.base_rounds: H['base_a'] = loop('base_a', 'base', 'none', noL, a.base_rounds)
    H['ins_a_sum'] = loop('ins_a_sum', 'ins', 'sum', noL, a.rounds)
    avals = [j * a.leb_step for j in range(int(sl.t / a.leb_step + 1e-9) + 1)] + [sl.t]
    nL = m.add_lebesgue(avals); log(f"+{nL} Lebesgue squares a in {[round(v, 4) for v in avals]}")
    H['ins_b_full'] = loop('ins_b_full', 'ins', 'full', noX, a.rounds)
    if a.rounds_b: H['base_b'] = loop('base_b', 'base', 'none', allc, a.rounds_b)
    final(([('base_a', 'base', 'none', noL, True), ('base_b', 'base', 'none', allc, True)] if a.base_final else []) + [
           ('ins_a_sum', 'ins', 'sum', noL, True), ('ins_a_none', 'ins', 'none', noL, False), ('ins_a_full', 'ins', 'full', noL, False),
           ('ins_b_full', 'ins', 'full', noX, True), ('ins_b_full_withX', 'ins', 'full', allc, False),
           ('ins_b_sum', 'ins', 'sum', allc, False), ('ins_b_full_noX_noL', 'ins', 'full', noLX, False)])
    pool.close(); pool.join()
    log(f"DONE cpu {cpu_now():.0f}s wall {time.time() - T0:.0f}s")
    json.dump(dict(args=vars(a), results=results, hist=H, cpu=cpu_now()), open(f"runs/{tag}.json", 'w'), indent=1)


# ============================================================================== insertion / bookkeeping
def insert_x(cov, t):
    """mu' = mu|_{x < t+1} + tau_1(mu|_{x >= t}) on [0, s+1] x [0, s] -- as a float Cover (horizontal pieces split
    at t and t+1).  The box is recorded by s (square); callers transpose to do y."""
    P, w = cov.P, cov.w
    keepP = P[:, 0] < t + 1; shP = P[:, 0] >= t
    P2 = np.r_[P[keepP], P[shP] + [1.0, 0.0]]; w2 = np.r_[w[keepP], w[shP]]
    segs = []; sw = []
    for (o, aa, t0, t1), m_ in zip(cov.segs, cov.sw):
        pieces = [(t0, t1, m_)]
        if o == 1:                                    # horizontal: split at t and t+1
            for b in (t, t + 1):
                nxt = []
                for u0, u1, mm in pieces:
                    if u0 < b < u1:
                        f = (b - u0) / (u1 - u0); nxt += [(u0, b, mm * f), (b, u1, mm * (1 - f))]
                    else: nxt.append((u0, u1, mm))
                pieces = nxt
            for u0, u1, mm in pieces:
                if u1 <= t + 1 + 1e-12: segs.append((1, aa, u0, u1)); sw.append(mm)
                if u0 >= t - 1e-12: segs.append((1, aa, u0 + 1, u1 + 1)); sw.append(mm)
        else:
            if aa < t + 1: segs.append((0, aa, t0, t1)); sw.append(m_)
            if aa >= t: segs.append((0, aa + 1, t0, t1)); sw.append(m_)
    rects = []
    for x0, x1, y0, y1, d in cov.rects:
        if x0 <= t and x1 >= t + 1: rects.append((x0, x1 + 1, y0, y1, d)); continue     # the two parts abut: one rect
        if x0 < t + 1: rects.append((x0, min(x1, t + 1), y0, y1, d))
        if x1 > t: rects.append((max(x0, t) + 1, x1 + 1, y0, y1, d))
    return Cover(cov.s + 1, P2, w2, np.array(segs).reshape(-1, 4), np.array(sw), rects)


def transpose(cov):
    P = cov.P[:, ::-1].copy()
    segs = cov.segs.copy(); segs[:, 0] = 1 - segs[:, 0]
    rects = [(y0, y1, x0, x1, d) for x0, x1, y0, y1, d in cov.rects]
    return Cover(cov.s, P, cov.w, segs, cov.sw, rects)


def insert_xy(cov, t):
    c1 = insert_x(cov, t)                    # [0, k+1] x [0, k]  (s field = k+1, but y extent is still k)
    c2 = transpose(insert_x(transpose(c1), t))
    c2.s = cov.s + 1
    return Cover(cov.s + 1, c2.P, c2.w, c2.segs, c2.sw, c2.rects)


def strip_masses(cov, t):
    """p_x = mu([t,t+1) x [0,k]), p_y, q = mu([t,t+1)^2) of a float Cover (segments split proportionally)."""
    def frac(u0, u1, a, b):
        return max(0.0, min(u1, b) - max(u0, a)) / (u1 - u0)
    x, y = cov.P[:, 0], cov.P[:, 1]
    ix = (x >= t) & (x < t + 1); iy = (y >= t) & (y < t + 1)
    px = float(cov.w[ix].sum()); py = float(cov.w[iy].sum()); q = float(cov.w[ix & iy].sum())
    for (o, aa, t0, t1), m_ in zip(cov.segs, cov.sw):
        ina = t <= aa < t + 1; f = frac(t0, t1, t, t + 1)
        if o == 0: px += m_ * ina; py += m_ * f
        else: py += m_ * ina; px += m_ * f
        q += m_ * ina * f
    for x0, x1, y0, y1, d in cov.rects:
        ox = max(0.0, min(x1, t + 1) - max(x0, t)); oy = max(0.0, min(y1, t + 1) - max(y0, t))
        px += d * ox * (y1 - y0); py += d * oy * (x1 - x0); q += d * ox * oy
    return px, py, q


def periodicity_defect(cov, k, nsamp=4001):
    """max |mu(A + e1) - mu(A)| over A = segments [u, u+h] x {line} / point sets / rect slices, A in [t, t+sqrt2]
    (sampled), for the vertical slab; the horizontal one by transposition.  0 means periodic (to float accuracy)."""
    t = (k - 1 - SQ2) / 2; worst = 0.0
    for cv in (cov, transpose(cov)):
        # horizontal lines crossing the vertical slab: F(u+1) - F(u) constant on [t, t+sqrt2]
        for (o, aa, bk, cum) in cv.lines:
            if o == 1:
                u = np.linspace(t, t + SQ2, nsamp)
                d = np.interp(u + 1, bk, cum) - np.interp(u, bk, cum)
                worst = max(worst, float(d.max() - d.min()))
        # vertical lines inside the slab: line a and a+1 identical cumulative functions
        vl = {round(aa, 9): (bk, cum) for (o, aa, bk, cum) in cv.lines if o == 0}
        yy = np.linspace(0, k, nsamp)
        for aa, (bk, cum) in vl.items():
            if t - EPS <= aa <= t + SQ2 + EPS:
                F0 = np.interp(yy, bk, cum)
                b2 = vl.get(round(aa + 1, 9)); F1 = np.interp(yy, *b2) if b2 else np.zeros_like(yy)
                worst = max(worst, float(np.abs(F0 - F1).max()))
            if t + 1 - EPS <= aa <= t + 1 + SQ2 + EPS and round(aa - 1, 9) not in vl:
                worst = max(worst, float(cum[-1]))
        # points
        P, w = cv.P, cv.w
        A = {(round(px_, 9), round(py_, 9)): ww for (px_, py_), ww in zip(P, w)}
        for (px_, py_), ww in A.items():
            if t <= px_ <= t + SQ2: worst = max(worst, abs(ww - A.get((round(px_ + 1, 9), py_), 0.0)))
            if t + 1 <= px_ <= t + 1 + SQ2: worst = max(worst, abs(ww - A.get((round(px_ - 1, 9), py_), 0.0)))
        for x0, x1, y0, y1, d in cv.rects:          # a rect restricted to the slab is x-periodic iff it spans it
            if x1 > t and x0 < t + 1 + SQ2 and not (x0 <= t + EPS and x1 >= t + 1 + SQ2 - EPS):
                worst = max(worst, d)
    return worst


def fscan(cov, nproc, deg_step=1.0, pitch=0.01, seed=0):
    """float validity scan (lattice at angle_list(deg_step) + polish of the worst 400 + tile + item3)."""
    pool = mp.get_context('fork').Pool(nproc); rng = np.random.default_rng(seed)
    thetas = [math.radians(d) for d in C.angle_list(deg_step)]
    outs = pool.map(LC._worst30, [(cov, th, pitch, (0.0, 0.0), None) for th in thetas])
    V = np.concatenate([o[0] for o in outs]); Q = np.concatenate([o[1] for o in outs])
    seeds = Q[np.argsort(V)[:400]]
    res = pool.map(LC._pol, [(cov, ch, int(rng.integers(1 << 30))) for ch in np.array_split(seeds, 2 * nproc)])
    curv = np.concatenate([q[3] for q in res]); cur = np.concatenate([q[2] for q in res])
    tq = LC.tile_poses(cov.s, 0.002, 0.01, [0.0, 1e-5, 1e-3, 0.01, 0.1, 0.5, 1.0])
    tv = np.concatenate(pool.map(LC._mass, [(cov, ch) for ch in np.array_split(tq, 2 * nproc)]))
    FQ = np.array(F.item3(cov.s, 0.002, [0.0, 1e-6, 1e-4, 1e-2]))
    fv = np.concatenate(pool.map(LC._mass, [(cov, ch) for ch in np.array_split(FQ, 2 * nproc)]))
    pool.close(); pool.join()
    j = int(curv.argmin())
    return dict(lat=float(V.min()), pol=float(curv[j]), pose=cur[j], tile=float(tv.min()), fam=float(fv.min()),
                min=float(min(V.min(), curv[j], tv.min(), fv.min())))


def load_mixed_rects(path):
    """mixed v1 file -> Cover; axis-parallel rectangle polygons become rects."""
    cv = MC.load(path); D, W = cv['D'], cv['W']
    P = np.array([[x / D, y / D] for x, y, _ in cv['points']]).reshape(-1, 2); w = np.array([ww / W for *_, ww in cv['points']])
    segs, sw = [], []
    for (X0, Y0, X1, Y1, ww) in cv['segments']:
        if X0 == X1: segs.append((0, X0 / D, min(Y0, Y1) / D, max(Y0, Y1) / D))
        else: segs.append((1, Y0 / D, min(X0, X1) / D, max(X0, X1) / D))
        sw.append(ww / W)
    rects = []
    for ww, vs in cv['polygons']:
        xs = sorted(set(v[0] for v in vs)); ys = sorted(set(v[1] for v in vs))
        assert len(vs) == 4 and len(xs) == 2 and len(ys) == 2, 'only axis rectangles'
        x0, x1, y0, y1 = xs[0] / D, xs[1] / D, ys[0] / D, ys[1] / D
        rects.append((x0, x1, y0, y1, ww / W / ((x1 - x0) * (y1 - y0))))
    return Cover(float(cv['s']), P, w, np.array(segs).reshape(-1, 4), np.array(sw), rects)


def report_insert(name, cov, nproc, deg_step, log=print):
    k = int(round(cov.s)); t = (k - 1 - SQ2) / 2
    px, py, q = strip_masses(cov, t); tot = cov.total()
    per = periodicity_defect(cov, k)
    log(f"{name}: k = {k}, t = {t:.6f}, total {tot:.6f}, saving {k * k - tot:.6f}; periodicity defect {per:.2e}")
    log(f"   p_x = {px:.6f}  p_y = {py:.6f}  q = {q:.6f};  p_x + p_y + q = {px + py + q:.6f}  vs 2k+1 = {2 * k + 1}")
    c2 = insert_xy(cov, t); tot2 = c2.total()
    log(f"   inserted box k+1 = {k + 1}: total {tot2:.6f} = total + {tot2 - tot:.6f} (p_x+p_y+q = {px + py + q:.6f}); "
        f"saving {(k + 1) ** 2 - tot2:.6f}")
    t2 = (k - SQ2) / 2
    px2, py2, q2 = strip_masses(c2, t2)
    log(f"   inserted box at its centred slab t' = {t2:.6f}: p_x {px2:.6f} p_y {py2:.6f} q {q2:.6f} (predicted p+q = {px + q:.6f}, "
        f"{py + q:.6f}, {q:.6f}); periodicity defect {periodicity_defect(c2, k + 1):.2e}")
    if deg_step:
        s0 = fscan(cov, nproc, deg_step); s1 = fscan(c2, nproc, deg_step)
        log(f"   float scan (angle step {deg_step} deg, pitch 0.01 + polish + tiles + item3): box k min {s0['min']:.6f}; "
            f"inserted box k+1 min {s1['min']:.6f} (lat {s1['lat']:.6f} pol {s1['pol']:.6f} tile {s1['tile']:.6f} fam {s1['fam']:.6f})")
    return dict(px=px, py=py, q=q, tot=tot, tot2=tot2)


def bookkeep(a):
    out = open(f"runs/s2_bookkeep.log", 'a')

    def log(msg): print(msg, flush=True); out.write(msg + '\n'); out.flush()
    log(f"== bookkeep {time.strftime('%F %T')}")
    for k in (4, 5, 7):
        cov = Cover(float(k), np.zeros((0, 2)), np.zeros(0), rects=[(0, k, 0, k, 1.0)])
        report_insert(f"Lebesgue [0,{k}]^2", cov, a.nproc, 0, log)
    cov = load_mixed_rects(os.path.join(HERE, 'qx2_data/L4_k02_box7.txt'))
    report_insert("qx2_data/L4_k02_box7.txt", cov, a.nproc, a.deg_step, log)
    log(f"cpu {cpu_now():.0f}s")


def insert_file(a):
    z = np.load(a.file, allow_pickle=True)
    cov = Cover(float(z['k']), z['P'], z['w'], z['S'], z['sw'], z['rects'])
    out = open(f"runs/s2_bookkeep.log", 'a')

    def log(msg): print(msg, flush=True); out.write(msg + '\n'); out.flush()
    log(f"== insert {a.file} {time.strftime('%F %T')}")
    report_insert(a.file, cov, a.nproc, a.deg_step, log)
    log(f"cpu {cpu_now():.0f}s")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='mode', required=True)
    R = sub.add_parser('run'); R.add_argument('tag'); R.add_argument('--k', type=int, required=True)
    R.add_argument('--q', type=int, default=50); R.add_argument('--no-split', action='store_true')
    R.add_argument('--col-pitch', type=float, default=0.05); R.add_argument('--cols-from', default=None)
    R.add_argument('--warm', default=None); R.add_argument('--warm-perang', type=int, default=300)
    R.add_argument('--rows-from', default=None); R.add_argument('--germ', action='store_true')
    R.add_argument('--deg-step', type=float, default=1.0); R.add_argument('--rounds', type=int, default=8)
    R.add_argument('--rounds-b', type=int, default=0); R.add_argument('--base-rounds', type=int, default=4)
    R.add_argument('--base-final', action='store_true', help='also re-solve the baselines on the final rows (slow; rows were pruned against the insertable LPs)'); R.add_argument('--min-rounds', type=int, default=3)
    R.add_argument('--tol', type=float, default=3e-4); R.add_argument('--viol-tol', type=float, default=0.02)
    R.add_argument('--no-colgen', action='store_true'); R.add_argument('--cg-want', type=int, default=150)
    R.add_argument('--leb-step', type=float, default=0.1)
    R.add_argument('--prune-at', type=int, default=70000); R.add_argument('--prune-keep', type=int, default=15000)
    R.add_argument('--prune-slack', type=float, default=0.003)
    R.add_argument('--nproc', type=int, default=3); R.add_argument('--seed', type=int, default=1)
    B = sub.add_parser('bookkeep'); B.add_argument('--nproc', type=int, default=8); B.add_argument('--deg-step', type=float, default=1.0)
    I = sub.add_parser('insert'); I.add_argument('file'); I.add_argument('--nproc', type=int, default=8)
    I.add_argument('--deg-step', type=float, default=1.0)
    a = ap.parse_args()
    if a.mode == 'run': run(a)
    elif a.mode == 'bookkeep': bookkeep(a)
    else: insert_file(a)


if __name__ == '__main__':
    main()
