import Sqpack.Exact.Batch.N17.C0

/-! Generated by `search/exact/lean_cert.py --split 25`: n = 17, the certificate in `Data`, squares checked in 1 chunks. -/

namespace UnitSquarePacking.EC.N17

set_option maxHeartbeats 0

theorem ok (i : Fin 17) : boxOK cert i = true ∧ rowOK cert i = true := by
  exact chunk_0 i (by omega) i.isLt

theorem boxes : ∀ i, boxOK cert i = true := fun i => (ok i).1

theorem rows : ∀ i, rowOK cert i = true := fun i => (ok i).2

/-- `s(17) ≤ S*`, `S*` the root of `pS` in `[4.6755300936, 4.6755300936]`. -/
theorem packs : ∃ s : ℝ, peval pS s = 0 ∧ (((46755300936045509516341111704831466487671/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ≤ s ∧ s ≤ (((46755300936045509516341113704831466487671/10000000000000000000000000000000000000000 : ℚ) : ℚ) : ℝ) ∧ Packs 17 s :=
  packs_exact cert pS _ _ (by decide +kernel) (by decide +kernel) (by decide +kernel) boxes rows
    (by decide +kernel)
    (by decide +kernel) (by decide +kernel)

end UnitSquarePacking.EC.N17
