import Sqpack.ExactQuad

/-! Generated by `search/exact/lean_cert.py` from `n-1.minpoly.json.gz`: register record n = 1, field degree 1, `S` of degree 1.
8 touching conditions are identities mod `f`, 19 are strict; walls and pairs: 0/1 squares and 0/0 pairs by rational shadows. -/

namespace UnitSquarePacking.EC.N1

set_option maxHeartbeats 0
set_option maxRecDepth 100000

noncomputable def cert : Cert 1 where
  f := [0, 1]
  a := 0
  b := 0
  S := [1]
  sq := ![⟨[(1/2 : ℚ)], [(1/2 : ℚ)], [0], 0, [1], [0], [1]⟩]
  sep := fun i j => (((![[]] : Fin 1 → List (ℕ × Bool × Fin 4)) i).find? (·.1 == j.val)).elim (true, 0) (·.2)
  encl := ![⟨((49999999999999999999/100000000000000000000 : ℚ), (50000000000000000001/100000000000000000000 : ℚ)), ((49999999999999999999/100000000000000000000 : ℚ), (50000000000000000001/100000000000000000000 : ℚ)), ((99999999999999999999/100000000000000000000 : ℚ), (100000000000000000001/100000000000000000000 : ℚ)), ((-1/100000000000000000000 : ℚ), (1/100000000000000000000 : ℚ))⟩]
  Sl := (99999999999999999999/100000000000000000000 : ℚ)

/-- The polynomial of `S` (ascending coefficients). -/
def pS : Poly := [(-1 : ℚ), 1]

end UnitSquarePacking.EC.N1
