#!/usr/bin/env python3
"""`Sqpack/V7/Main.lean`: the root grid of run V3 glued into the D4 root, the face `θ = 0`, and
`Valid7` (hence `s(k² − 3) = k` for all `k ≥ 6` by `Bentz.bentz_of_valid7`).

    gen_main.py [OUTDIR]
"""
import os, sys
from fractions import Fraction as F

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from tree_rebuild import load  # noqa: E402
from run_v7 import LEAVES, SG, RG, MQ  # noqa: E402

D, W = 5, 10 ** 12
Q = D * SG


def main(outdir):
    roots = [(i, r) for i, (r, l, u) in enumerate(load(LEAVES))]
    xs = sorted({r[0] for _, r in roots} | {r[1] for _, r in roots})
    ys = sorted({r[2] for _, r in roots} | {r[3] for _, r in roots})
    us = sorted({r[4] for _, r in roots} | {r[5] for _, r in roots})
    at = {(xs.index(r[0]), ys.index(r[2]), us.index(r[4])): i for i, r in roots}
    assert len(at) == (len(xs) - 1) * (len(ys) - 1) * (len(us) - 1) == len(roots)
    iq = lambda x: int(x * Q)
    ir = lambda u: int(u * RG)

    def glue(a0, a1, b0, b1, c0, c1):
        if a1 - a0 == 1 and b1 - b0 == 1 and c1 - c0 == 1:
            return f"root_{at[(a0, b0, c0)]:05d}"
        if c1 - c0 > 1:
            m = (c0 + c1) // 2
            return f"(CovT.splitU {ir(us[m])} {glue(a0, a1, b0, b1, c0, m)} {glue(a0, a1, b0, b1, m, c1)})"
        if a1 - a0 >= b1 - b0:
            m = (a0 + a1) // 2
            return f"(CovT.splitX {iq(xs[m])} {glue(a0, m, b0, b1, c0, c1)} {glue(m, a1, b0, b1, c0, c1)})"
        m = (b0 + b1) // 2
        return f"(CovT.splitY {iq(ys[m])} {glue(a0, a1, b0, m, c0, c1)} {glue(a0, a1, m, b1, c0, c1)})"

    assert xs[0] == 0 and ys[0] == 0 and us[0] == 0 and xs[-1] == ys[-1] == F(7, 2) and us[-1] == F(1, 2)
    half = MQ * SG - MQ * SG // 2
    lines = ["import Sqpack.V7.Face", "import Sqpack.V7.Bridge", "import Sqpack.ValidSplit7"]
    lines += [f"import Sqpack.V7.R{i:05d}" for i, _ in roots]
    lines += ["", "/-!", "# `Valid7`, kernel-checked", "",
              "The pose trees of `qx2_zm` run V3 (`certificates/k2m3/qx2_zm`), one module per root",
              "(`R?????.lean`, generated by `scripts/run_v7.py`), glued over the D4 root `[0, 7/2]² × (0, 1/2]`;",
              "the face `θ = 0` (`Face.lean`, Lemma Z); the box file as the cover (`Bridge.lean`). -/", "",
              "namespace SquarePacking", "namespace LemmaELeaf", "open ZMTreeM ZMTree", "",
              f"theorem v7_tree : CovT {D} {SG} {MQ} {RG} {W} [] tsegs trects 0 {half} 0 {half} 0 {RG // 2} :=",
              f"  {glue(0, len(xs) - 1, 0, len(ys) - 1, 0, len(us) - 1)}", "",
              "/-- **`Valid7`**: every closed unit square in `[0,7]²` has mass `≥ 1` under the box measure. -/",
              "theorem valid7 : Bentz.Valid7 := by",
              f"  have hc := cover_of_tree {D} {SG} {MQ} {RG} {RG // 2} {W} PTree.leaf segsT trects",
              "    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)",
              "    (by decide +kernel) (by decide)",
              "    (by rw [segsT_toList]; exact face_root) (by rw [segsT_toList]; exact v7_tree) (by decide)",
              "  intro c θ hsub",
              "  rw [box7Cover_eq_mcoverP]",
              "  exact hc c θ (by norm_num; exact hsub)", "",
              "/-- **`s(k² − 3) = k` for every `k ≥ 6`**, with no hypothesis. -/",
              "theorem bentz : ∀ k : ℕ, 6 ≤ k → minSide (k ^ 2 - 3) = k := Bentz.bentz_of_valid7 valid7", "",
              "/-- **`ValidTilt7`** (`ValidSplit7.lean`): the tilted run's region, a special case of `valid7`. -/",
              "theorem validTilt7 : Bentz.ValidTilt7 := by",
              "  intro c u _ _ _ _ hsub",
              "  exact valid7 c _ hsub", "",
              "end LemmaELeaf", "end SquarePacking"]
    open(os.path.join(outdir, "Main.lean"), 'w').write("\n".join(lines) + "\n")
    print(len(roots), "roots;", len(xs) - 1, len(ys) - 1, len(us) - 1)


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', 'Sqpack', 'V7'))
